### ISSUE TITLE
Bug: Image element src not in sync when replaced with other media

### ISSUE THREAD

**Issue by maxyinger** [swissspidy/web-stories-wp#10192]
Found in this thread here once we fixed some bugs with the animation provider:
https://github.com/google/web-stories-wp/pull/10024#issuecomment-1012362521

When replacing an image element with new media, the src remains on the old resource while the srcset updates to the new resource.

Visually there are no issues because the browser pulls the currentSrc from the srcset instead of the src, but src resource shouldn't get out of sync with the active resource. 

Completion of this ticket involves updating `story-editor/src/elements/media/imageDisplay.js` to maintain the active resource as its src and to re-enable these karma tests to make sure they're passing:
- should correctly copy image to page with existing image
- should correctly handle image dragged from library straight to edge replacing old image
- should correctly handle image dropped on edge replacing old image
- should replace top image when bg image is set and another one is on top
- should replace the top image when two images are in the same place on canvas

This behavior can't be seen on the canvas until this PR is merged, but you can view it on main right now in the carousel page preview after replacing media of an element:
https://github.com/google/web-stories-wp/pull/10024

**Comment by miina** [comment]
@merapi I'm adding this to Ready for Sprint right now, leaving you assigned in case you have any insight into it to add to the issue (since the [last relevant changes](https://github.com/google/web-stories-wp/pull/10024#issuecomment-1012409034) seem to be by you).

Otherwise, we can just investigate as soon as there's availability from the current sprint issues.
