### ISSUE TITLE
Video Trimmer: bail early if original video does not exist

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10245]
## Feature Description

The `useVideoTrimMode` tries to load information from the original untrimmed video (if `trimData.original` is set), but does not cater for a case where the original video has since been deleted.

https://github.com/google/web-stories-wp/blob/456348dc59a45d22783a3a587768adaaec821a90/packages/story-editor/src/components/videoTrim/useVideoTrimMode.js#L76-L94

We should add some `catch()` there in to properly handle that case.

**Aside**: might be worth checking whether the component is still mounted before updating the state.

**Comment by barklund** [comment]
@swissspidy, the second argument to `.then()` is [a catch function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then), so a deleted or otherwise unavailable original media item is handled in these lines:

https://github.com/GoogleForCreators/web-stories-wp/blob/456348dc59a45d22783a3a587768adaaec821a90/packages/story-editor/src/components/videoTrim/useVideoTrimMode.js#L89-L90

**Comment by swissspidy** [comment]
Wow how could I miss that 🤦‍♂️
Then it seems like we‘re all good here?

**Comment by barklund** [comment]
> Then it seems like we‘re all good here?

Yeah, I think it works as expected. I tested this originally by manually editing the original id to a non-existent element, and it seemed to handle that correctly.

**Comment by swissspidy** [comment]
@miina perhaps you can double check with what you've experienced and confirm that all is good indeed?

**Comment by miina** [comment]
Yep, seems to be working ok currently when the origin video is deleted. Closing the issue.
