### ISSUE TITLE
History: Investigate actions still causing history pollution

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#10289]
## Feature Description
There are a few actions that still cause history pollution. It would be good to investigate those and ensure that if user does an action, just one Undo would revert it. Currently, some actions require multiple clicks of "Undo".

Known actions:
- Uploading Video directly onto a Page
- Removing audio from a video
- Trimming a video

There might be more.

## Additional Context
See [GH conversation here.](https://github.com/google/web-stories-wp/pull/10240#issuecomment-1016894611)

**Comment by timarney** [comment]
> Uploading Video directly onto a Page

Digging into this --

We can remove one entry by adding `resource.isOptimized` to `useHistoryEntry.js`

There's another entry that happens when optimizing a video --- 

If you undo from that entry you end up with a broken state as the blob resource can't be found.

Looking into how that entry could be avoided. 

<img width="1777" alt="Screen Shot 2022-06-07 at 9 12 15 AM" src="https://user-images.githubusercontent.com/62242/172389222-5644ecab-ccfd-4791-b0f1-4e3b9380e8a3.png">

**Comment by swissspidy** [comment]
> If you undo from that entry you end up with a broken state as the blob resource can't be found.

If you undo again, will you get back to the original, unoptimized video?

> Looking into how that entry could be avoided.

Wondering if we would need to add some special handling for that case, since just adding `'resource.src'` to `ELEMENT_PROPS_TO_IGNORE` probably does not work, since during optimization the resource ID will change as well (from a temp uuid to a WordPress database ID), and perhaps other keys too.

**Comment by felipebochehin87** [comment]
Added images, videos, shapes, text and stickers
Resized, changed colors, added audios, captions, trimmed, added borders, changed opacity, fonts, styling
Undo, redo, undo again, delete all, started from scratch.

Looks good in QA.
