### ISSUE TITLE
Media: Transcoded asset hang and never complete

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#10301]
## Bug Description

Found as part of testing https://github.com/google/web-stories-wp/pull/10001. 

Transcoded videos, sometimes hang and never complete. The save button does is disable as well. 

Possibly related to https://github.com/google/web-stories-wp/pull/9999

## Steps to Reproduce

1. Create story. 
2. Drag 5 images into canvas. 
3. Drag 5 videos into canvas. 

See video 

## Screenshots

https://user-images.githubusercontent.com/237508/150521275-dd2e9b09-eb9f-484a-a36f-2dc921525586.mov

## Additional Context

- Plugin Version: 17.0.0-alpha
- WordPress Version: 5.8/5.9RC3
- Operating System: Mac OS
- Browser: Chrome / Safari

**Comment by swissspidy** [comment]
Can you confirm that it really, really hangs and never completes? Not even after 5 or like 30 minutes?

I am asking because media transcoding happens in sequence now, one after the other. So it takes a bit longer. And you stopped the video after just 40s

Also, can you re-test this again in a production build? The above video clearly shows you're running a development build, which is usually much slower.

**Comment by swissspidy** [comment]
I continue to be unable to reproduce this in any browser; transcoding/uploading is never stalling or anything for me. Not even in a development build. I tested in the docker container, in LocalWP, and on stories-new without issues.

I worry that there is some race condition somewhere that makes this so difficult to reproduce, but that would require some debugging to find out.

Since this is apparently consistently failing for you, it would be great if you could do that debugging in the media upload queue (timeboxed to a couple of hours perhaps) and report any findings here.


B.Matt mentioned on Slack that video upload was rather slow for him but definitely eventually finishes. To remedy that, we could try to transcode more than 1 item in parallel if the hardware allows for that (using `navigator.hardwareConcurrency`).
