### ISSUE TITLE
RightClickMenu refactor to use isMediaUpload

### ISSUE THREAD

**Issue by merapi** [swissspidy/web-stories-wp#10393]
## Feature Description

Right now Empty State menu uses `enrich` [approach](https://github.com/GoogleForCreators/web-stories-wp/pull/10261/#discussion_r791112921). This ticket is about refactoring that to `isMediaUpload` [solution](https://github.com/GoogleForCreators/web-stories-wp/pull/10261/#discussion_r791125731) ideally with unifying the `pageSideMenu` media upload usage. This will need its own round of testing/reviews.

Extracted from https://github.com/GoogleForCreators/web-stories-wp/pull/10261/#discussion_r791125731
Comment removed because it does not apply now.

**Comment by samwhale** [comment]
#9960 refactored the context menu so that custom menu items could be rendered within the context menu. One may render anything they'd like inside the menu, but components are provided that
1. Meet accessibility standards
2. Are styled according to designs in figma
3. Hooked into the context menu provider. This provides closing and focus functionality that's consistent with the rest of the menu.

I don't think this ticket is necessary, but let me know if I'm missing something.

**Comment by merapi** [comment]
Instead of `isMediaUpload` solution we something else in https://github.com/GoogleForCreators/web-stories-wp/pull/10261/commits/63391c8f60b7d958c858669c5680d713e946c962

```jsx
<ContextMenuComponents.MenuButton ... />
<LibraryProvider>
  <MediaButton />
</LibraryProvider>
<ContextMenuComponents.MenuButton ... />
```

So this ticket is just/more about the unifying part now?
