### ISSUE TITLE
Page Templates:  thumbs keep "jumping" when you try to apply a template 

### ISSUE THREAD

**Issue by bmgoss** [swissspidy/web-stories-wp#10437]
## Bug Description
When I scroll through the Page Layouts, apply one page, then scroll through it again and click on a different thumb layout, the scroll jumps to a different position, and does not apply the layout I want. This happens when I am using my own saved templates, not the models available. When I use the keyboard, it doesn't happen.

## Expected Behaviour
To be able to choose a template, use it and not have it jumping when I select a template on my saved models. 

## Steps to Reproduce

Apply a template, confirm, scroll and click on a different page template on my saved models. 

## Screenshots

https://drive.google.com/file/d/1kwoQXDtEwBluYODg6-GlAizJ3GoQCSft/view?usp=sharing

## Additional Context

- Plugin Version: 1.16.0
- WordPress Version: 
- Operating System: Windows 10 Pro
- Browser: Chrome 97.0.4692.99

**Comment by swissspidy** [comment]
Thanks a lot for your thorough bug report and the video!

I am able to reproduce this issue here as well. The scrolling is definitely quite odd.

We'll look into this.

----

@BrittanyIRL is this something your pod could prioritize for next sprint?

Here's another demo of janky scrolling behavior:

https://user-images.githubusercontent.com/841956/152162302-3aff852e-fb63-4cff-a85f-c2c603c87889.mov

**Comment by BrittanyIRL** [comment]
oof that's no good, yup! we'll prioritize this for next sprint.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10764.

Scrolling looks good on Firefox, Chrome and Safari
Regressed saved templates - add, edit and remove
