### ISSUE TITLE
Links: Add special handling for Instagram when retrieving metadata

### ISSUE THREAD

**Issue by adamdunnage** [swissspidy/web-stories-wp#10451]
## Feature Description

As requested by the user in [this support topic](https://wordpress.org/support/topic/about-link-information-from-another-site-in-editor/#post-15324280), could we add some special handling for Instagram links to fix the text link optional description box auto populating with text.

## Alternatives Considered

N/A

## Additional Context

User initially asked if it was possible to disable this automatically fetching text for the optional description box as well as the optional brand icon. After discussing with @swissspidy he suggested that we could add a special handling for Instagram links to fix the text link optional description box auto populating with text.

**Comment by swissspidy** [comment]
Apparently some Instagram profiles are public, see https://help.instagram.com/116024195217477 for an explanation. But the ones I tried are all behind the login.

**Comment by swissspidy** [comment]
## Implementation Brief

When linking to `https://www.instagram.com/googleforcreators/` or some other profile, you might land on the login page and get `Log In` as the link description.

To avoid this, let's adjust `Link_Controller` logic so that when a link to `https://www.instagram.com/googleforcreators/` doesn't land on the profile, we return a custom link description like `Instagram - @googleforcreators` instead of the `Log In` title you would get otherwise.

Can be done hardcoded in the controller, or using a filter, whatever makes most sense.

**Comment by spacedmonkey** [comment]
I have done some testing on these on the ticket. The issue here, I believe that instagram does not want script to scrap their site, so just redirects the request to a page with 405 requesting the user logs in. Strangely, even through the redirect hits a 405 error state along the way, it seems to return a 200 state still. Maybe to ensure that is doesn't get hit for SEO juice, by returning 405 or auth errors. 

Another workaround for this issue, would be to only allow for the request on the url to redirect once. By tweaking this, it means the multiple redirects would not resolve and the scrap will correctly error out. 

This also means the facebook link, also shared in the support through, would also error out. Is this a better solution for the problem as a whole, instead of the workaround documented here.

**Comment by swissspidy** [comment]
We should short-circuit so that no HTTP requests are made in the first place.
