### ISSUE TITLE
Discovery: Consider using Puppeteer Testing Library

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10473]
## Task Description

With Puppeteer Testing Library ([`pptr-testing-library`](https://www.npmjs.com/package/pptr-testing-library)) we could bring our e2e test suite closer to our karma and unit test suites, making it easier to write write tests for all three targets.

Let's do a brief evaluation and perhaps rewrite a few e2e tests to see how well it works. If successful, we can update all of the tests.

**Comment by spacedmonkey** [comment]
Related: https://github.com/WordPress/gutenberg/issues/27260 https://github.com/WordPress/gutenberg/pull/28380

**Comment by spacedmonkey** [comment]
So my thoughts on the [pptr-testing-library](https://www.npmjs.com/package/pptr-testing-library). 

Even though it seem very well documented etc, I can't find many people talk about or using this library online. This is worrying, as it does not have the community around it I would like. Looking at the release history, there was one release 4 months ago and the one before that, was 25 May 2021, so not supported / well maintained either. 

Of the 127 project that use this library, this is because there are using some kind of react based boilerplate that uses it. Not that it used actively. I have seen this [file](https://github.com/sanjugit11/DaoFrontend/blob/main/tests/e2e/testHelpers.ts) repeated a lot. 

This includes, the following snippet. 

```js
export const getByTestId = async (page: Page, testId: string): Promise<ElementHandle> => {
  const document = await getDocument(page);
  return queries.getByTestId(document, testId);
};
```

This shows up one of the issues, using this library, the interface. Unlike in karma tests, the document has be collected and passed as an arg into the query. Ideally, the interface would look like this. 

```js
page.getByTestId(testId);
```

There is `pptr-testing-library/extend` that add a similar looking interface. 
See example. 

```js
const $document = await page.getDocument();
const $form = await $document.getByTestId('my-form');
```

However, I was unable to get `pptr-testing-library/extend`  working in our setup. There is no documentation other then the readme for it. I fear, if I did implement it, would likely break the existing tests we have meaning we would have to write them. 


I also did not find the function is gave super useful. In my example PR. https://github.com/GoogleForCreators/web-stories-wp/pull/10900. Used the following functions. 

- getByTestId,
- getByAltText,
- getByText,
- getByLabelText

These functions were useful to a point, for very simple queries by alt, testId or aria label. For were extremely restricting, for more complex queries by attribute or nested element. I personally found it much harder to use and understand than the existing tests. 

I personally see little benefit of using this library, as converting all tests at once, is a big ask, for little improvement in usability / speed / readability in tests.

**Comment by swissspidy** [comment]
Thanks for looking into it.

Sounds like it's not a good match for us right now.

I am not too worried about maintenance, given that the package is only a very thin wrapper around TL to expose some functions, so it doesn't really need frequent updates.

> However, I was unable to get `pptr-testing-library/extend` working in our setup.

FWIW, it should be as simple as adding `import 'pptr-testing-library/extend';` in `bootstrap.js`.
