### ISSUE TITLE
Media: Add support for hotlinking VTT files

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#10515]
## Feature Description

As a publisher who leverages remote asset hosting we depend on “insert by URL” functionality to support using videos in our Web Stories. As such, it would be great for the plugin to also support the use of remotely hosted VTT files by being able to supply a URL for these as well in the Caption VTT file selector.

**Comment by swissspidy** [comment]
Sounds like a reasonable feature request. Should be easy to implement. Just needs design.

For reference, right now we have a simple button that opens a media picker:
![Screenshot 2022-02-09 at 14 27 39](https://user-images.githubusercontent.com/841956/153211026-4f98374a-3d9c-4cd9-bd93-6707e79b988d.png)

Suggestion:

We could change this button so that it opens a dropdown with two options:

1. Upload file - same as today
2. Insert from URL - this will open a modal with an input field for the URL (similar to media hotlinking)

cc @aaskedall @gajasinski

**Comment by gajasinski** [comment]
@swissspidy seems reasonable. @agingoldseco @aaskedall for thoughts.

Happy to prioritize this accessibility work.

**Comment by swissspidy** [comment]
@agingoldseco @aaskedall Friendly ping, this one still needs some design

Right now what we have is this:

https://user-images.githubusercontent.com/237508/161045350-f28b6eb5-5e2b-47f9-a58e-aa138d55893a.mov

The wording can probably improved and perhaps we can also use buttons with icons instead of labels.

**Comment by agingoldseco** [comment]
Any reason people might want to rename it after upload? I can see that, reopening the link modal, or viewing info about it being reasons to make it clickable. Otherwise, I can work on ways to just make it look less clickable. 

I actually don't mind the text buttons—they're straightforward and go with the rest of the panel. Making them a dropdown might be needlessly adding a click. 

We could potentially add a little blurb about captions to explain why they're good to include for accessibility.

**Comment by swissspidy** [comment]
Renaming is not necessary / not relevant. But being able to click on it to view details (or even replace it) would be nice. Right now it's not possible to do that. You can't even tell whether `wst024_page2_my_captions.vtt` (from the screenshot above) is from my WP media library or hotlinked from somewhere else.

> We could potentially add a little blurb about captions to explain why they're good to include for accessibility.

Just noting that we already have a checklist item for captions.

**Comment by bmattb** [comment]
@agingoldseco have you had a chance to work on this at all?

**Comment by spacedmonkey** [comment]
I strongly recommend, that we keep the UX for all hotlinking the same, so audio, caption and image / video using a similar looking UX. There is no need for these dialogs to be different in different complex and just adds unneeded complexity.

**Comment by swissspidy** [comment]
@aaskedall @agingoldseco I created a prototype at #11468 in case you wanna take a look.

**Comment by spacedmonkey** [comment]
At some point, it would be great to support hotlink in the poster functionality. Posters are used for the story and videos. 
<img width="140" alt="Screenshot 2022-05-10 at 14 16 32" src="https://user-images.githubusercontent.com/237508/167637407-da7dc815-65ed-4d39-a1cc-951cf2f253cc.png">
