### ISSUE TITLE
Editor: Add CORS issue detection

### ISSUE THREAD

**Issue by mxbclang** [swissspidy/web-stories-wp#10529]
## Feature Description

Especially since the addition of video optimization, the support team regularly receives questions from users regarding CORS errors and why their videos/images are not displaying when using the Media Library in the Web Stories Editor:

- https://wordpress.org/support/topic/images-wont-upload-and-dont-show/
- https://wordpress.org/support/topic/unable-to-access-images-in-stories/
- https://wordpress.org/support/topic/video-issues-after-updating-to-1-13-0/
- https://wordpress.org/support/topic/blocked-by-cors-policy-if-stored-images-on-s3/

Users often think of this as a "sudden" change after they have begun offloading their images to S3 or another external source, and they don't make the connection between their offloading changes and the missing images.

As discussed with @swissspidy in our support/eng meeting on 9 Feb, it would be great to add some kind of detection in the Editor to tell that a user is offloading their media and prompt them to adds CORS headers to fix the display issues, e.g.: 

"It looks like you're offloading your site's images and media to another server, which is keeping them from displaying properly within the Web Stories Editor. To fix this issue, please contact your web developer or hosting provider and ask them to set up a CORS header."

Most of our users are offloading to S3, so may be helpful to link to their guide on CORS: https://docs.aws.amazon.com/AmazonS3/latest/userguide/cors.html.

**Comment by spacedmonkey** [comment]
It is worth noting that I personally had this problem. I was offloading all the my media assets to [digital ocean spaces](https://docs.digitalocean.com/products/spaces/). This is very similar to S3. Setting up CORS headers, took me a very long time to workout. Part of the issue was that, changing cors headers, was only reflected on new images / videos uploaded. The cors settings are stored per image / video in the bucket. I had to workout a way, retro-actively update all existing media for the editor to work correctly. 

We already have a CORS proxy, there is something stopping us to a check on every asset to ensure that there is no cors issues. 

We could also do a simple check to see if the upload url ( see [wp_upload_dir](https://developer.wordpress.org/reference/functions/wp_upload_dir/) ) is the same a site url ( see site_url ). For example, for my site, my assets are on the domain assets.computingcorner.co.uk and the site url is spacedmonkey.com. If those two domains are different, it is extremely likely that assets are being offloaded and the cors proxy may have to be used for all assets.

**Comment by swissspidy** [comment]
Thanks for chiming in with potential implementation ideas.

I want to avoid papering over these issues by simply using the CORS proxy (not to mention the performance concerns), which is why I want to have an error message instead. Just like we do with the `StatusCheck` component.

**Comment by spacedmonkey** [comment]
How about we do some kind of check when the editor opens. Check to see if upload url  and site url are different. If different. then do a check on the first item in the media library. If we get a cors error, then show a message. Something like that?

**Comment by swissspidy** [comment]
That's more or less what I had in mind, yes. Thus just like `StatusCheck`.

I am going to write down some acceptance criteria & implementation brief soon.
