### ISSUE TITLE
Support the ability to select and apply animation changes across multiple pages & elements

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#10577]
## Feature Description

As a publisher who uses animations throughout their stories, we would like improvements made to support the ability to select and apply animation changes across multiple pages and elements. Specifically the use cases that we would like to support are:

- As an editor, I would like the ability to select multiple elements that exist within a page OR across multiple pages and apply a specific transition to them. This will override any existing animations on them.  For example, Page 1 has 3 animations, Page 2 has 1 animation - I would like to be able to select one of the animations on Page 1 and the animation on Page 2 and change it to another animation in one go. 
- As an editor, I would like the ability to select multiple pages and apply a specific transition to them. This will override any existing animations on them and apply to all transitions on selected pages. For example - my web story contains 8 pages, all with animations. I'd like to select all 8 pages and apply an animation to them in one go. 
- As an editor, I would like the ability to select multiple pages and remove animations on them.

CC: @aaskedall @gajasinski

**Comment by swissspidy** [comment]
I would love to hear more about where this is coming from. Is this just about workflow speed / saving time?

Removing all animations everywhere might be useful, but I don‘t see the benefit in applying the same animation to multiple elemts across pages.
In fact, we discourage doing that as it makes for poor UX due to repetitive animations. It‘s better to use different ones. But also, less is more.

Aside: we don‘t currently offer any way to edit multiple pages at once in the editor, so this would be a novum.

**Comment by bmattb** [comment]
@swissspidy after further discussion this evening with the Newscorp team, it was agreed that they would be happy with just the ability to leverage group animations which is still hinted at in the editor as coming soon (ref - https://github.com/googleforcreators/web-stories-wp/issues/4105) 
![multi-animations](https://user-images.githubusercontent.com/58738530/155632563-1f44605c-f81b-4d73-8243-f32307634247.png)

Let me know what you would like to do with this ticket.

**Comment by swissspidy** [comment]
I didn't realize the editor says "Group animation support coming soon" 😄  We should probably just remove that text to declutter the UI.

Since this would involve the Animation Timeline (see #3414), we should clarify where we see this on the roadmap. Then we can reopen that ticket & close this one as a duplicate.

cc @gajasinski for input

Mockup of Animation Timeline for context:

<img src="https://images.zenhubusercontent.com/5b35729a5b51b10bd4dd5fd1/e784f266-ce96-471a-8c24-7e9f8a26c540" width="400">

**Comment by gajasinski** [comment]
@swissspidy thanks for the mocks. depending on other priorities, I could see this animation timeline being within a Q2 scope. We could then prioritize the grouping of elements as a part of that. @aaskedall @agingoldseco - thoughts here on the complexity? Does this help or hurt our goal of reducing the overuse of the same animation across all pages?

**Comment by swissspidy** [comment]
Closing in favor of #11310
