### ISSUE TITLE
FontProvider creating endless loop

### ISSUE THREAD

**Issue by c0b41** [swissspidy/web-stories-wp#10596]
Standalone editor, font provider calling getFonts function and creating endless loop.
This code block creating endless loop.

https://github.com/GoogleForCreators/web-stories-wp/blob/2f73bb644cf2313672e344891c02c7c838be08d4/packages/story-editor/src/app/font/fontProvider.js#L54-L85

## Steps to Reproduce
https://codesandbox.io/s/laughing-heyrovsky-eefv2

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Same here, very useful feedback, thanks a bunch!

We should only attempt to do this once.

Even better, we should address this open todo by not loading fonts if not really needed:

https://github.com/GoogleForCreators/web-stories-wp/blob/2f73bb644cf2313672e344891c02c7c838be08d4/packages/story-editor/src/app/font/fontProvider.js#L56-L57

**Comment by mohdsayed** [comment]
How these two effects are working is quite confusing to me.
https://github.com/GoogleForCreators/web-stories-wp/blob/7118b139d44f6985b915c9bea2d3a3cd80f976d5/packages/story-editor/src/app/font/fontProvider.js#L54-L120

By using `let mounted = true; ` I assume we want to run it only once when the component mounts however instead of using `  const mounted = useRef( false )` outside, we are settings `let mounted = true;` inside the `useEffect` callbacks  and why the first `useEffect` is getting called without `[]` 🤔 . If it was getting called only once, it should never go in an infinite loop.

> Even better, we should address this open todo by not loading fonts if not really needed

@swissspidy Can you explain this a bit more? 

One quick fix can be this https://github.com/GoogleForCreators/web-stories-wp/pull/10643

**Comment by swissspidy** [comment]
Sure, happy to provide some context.

So the idea here was to basically load the list of custom fonts in this provider just once when the component mounts.

The `let mounted` check was added later to prevent "Can't perform a React state update on an unmounted component" warnings.

Note: In hindsight using `useMemo` would probably be better.

----

The problem with the current implementation is that it doesn't work well in a decoupled context where `getFonts` is not available (hence the ` && get Fonts &&` check as a workaround). Also, it makes an unnecessary HTTP request even when not actually using fonts in the editor.

In the editor, the custom fonts are only actually needed by the `FontPicker` component:

https://github.com/GoogleForCreators/web-stories-wp/blob/6105559dedb9f7401a0e5803e3130d63ff0028dc/packages/story-editor/src/components/panels/design/textStyle/fontPicker.js#L50-L70

https://github.com/GoogleForCreators/web-stories-wp/blob/6105559dedb9f7401a0e5803e3130d63ff0028dc/packages/story-editor/src/components/panels/design/textStyle/fontPicker.js#L151-L171

The same goes for `curatedFonts` as well.

To fix this, we potentially could remove those effects in `FontProvider` and instead turn them into two `getCuratedFonts` and `getCustomFonts` actions.

Then, the `FontPicker` component would call these within a `useMemo()` so these fonts are only loaded when needed.

WDYT?

**Comment by mohdsayed** [comment]
> To fix this, we potentially could remove those effects in FontProvider and instead turn them into two getCuratedFonts and getCustomFonts actions.

That's a good idea 👍 

> The let mounted check was added later to prevent "Can't perform a React state update on an unmounted component" warnings.

Are you sure it works? I tried to log the value of `mounted` when the component unmounts, by delaying the request by 3-4 seconds. The value of `mounted` never changed to `false`. Ideally, [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort) or something should have been used to cancel the request on unmount however since our fetch request will be made by the consumer package, it will complicate things to ask for it. I am going to use `const mounted = useRef( false )` outside the effect hook, which should serve the purpose.


> Then, the FontPicker component would call these within a useMemo() so these fonts are only loaded when needed.

How do we want to use `useMemo`? Did you mean like this?

```js
  useMemo(() => {
    getCustomFonts();
    getCuratedFonts();
  }, [getCustomFonts, getCuratedFonts]);
```

( Updated https://github.com/GoogleForCreators/web-stories-wp/pull/10643 )

**Comment by swissspidy** [comment]
Yes `AbortController` would definitely be better.

I think what you currently have in your PR looks good 👍 

Initially thought about handling the customFonts/curatedFonts state in FontPicker but it makes sense to keep that as-is. So all good there.
