### ISSUE TITLE
UI Simplification: Floating menu bar

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#10640]
## Feature Description
See [Figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=11394%3A457049)

Full Todo list:

- [x] Add this behind a Feature flag to release together with #10111 
- [x] Add a floating menu bar that is opened by default.
- [x] When closing the menu bar, it can be opened again by re-selecting the element, it will always be open for the element that gets selected.
- [x] Add items to the menu bar based on Figma -- these will not be links as in quick-action menu but can be directly edited from the bar.
- [ ] Note: Border and Corner inputs are only displayed when locked. If unlocked, don't display these in the menu.
- [x] When clicking on "More" button, it will open and highlight the Design Panel
- [x] Use flyouts as in Figma
- [x] Replace button for media edit bar -- replaces the media, keeping other props the same as possible.
- [x] Remove duplicates from the quick-action menu.

Duplicated to remove:
- From text element, remove: Change Color; Edit Text
- From shape element, remove: Change Color
- From video, remove: Trim

**Comment by BrittanyIRL** [comment]
Differences noted 3/18 vs initial feature description: 
- While corner is only displayed when locked, border remains visible regardless - to me this seems like there was maybe a discussion that wasn't visibly documented between prom and design. 
-  Media button in floating menu was abandoned in favor of the quick actions because of background media, so that shouldn't be visible ever in floating menus. 

Moving outside of this release: 
- Flyouts (needs UX description of what this should look like - new ticket here: https://github.com/GoogleForCreators/web-stories-wp/issues/10987)
- Keyboard navigation (#10872 ) 

Screenshot from [figma ](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=11122%3A443753) for quick reference. 
<img width="878" alt="Screen Shot 2022-03-18 at 12 09 14 PM" src="https://user-images.githubusercontent.com/10720454/159069331-7fa3bc3b-0e03-4e42-99a3-fb3184cfcbad.png">

**Comment by miina** [comment]
@BrittanyIRL 
I had forgotten my email open, saw your comment and couldn't resist answering 😛 (Closing it now after this comment!)

> While corner is only displayed when locked, border remains visible regardless - to me this seems like there was maybe a discussion that wasn't visibly documented between prom and design.

The difference comes from implementation inconsistency: corner radius checks if it's locked to display/not while border checks for all borders being equal / not instead of locked. Per UX guidelines both corner and border inputs should be hidden when unlocked (UX hasn't specified if we should check for all values being equal as well).

**Comment by BrittanyIRL** [comment]
> The difference comes from implementation inconsistency: corner radius checks if it's locked to display/not while border checks for all borders being equal / not instead of locked. Per UX guidelines both corner and border inputs should be hidden when unlocked (UX hasn't specified if we should check for all values being equal as well).

Ah then this is a bug! I'll make a new ticket.
