### ISSUE TITLE
Background Audio: Enable new features by default

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#10689]
## Task Description

For 1.19.0 we want to enable the background audio improvements (captions + non-looping support) by default, [as per the documentation](https://github.com/GoogleForCreators/web-stories-wp/blob/main/docs/feature-flags.md#enabling-feature-flags-by-default).

**Comment by felipebochehin87** [comment]
@swissspidy @timarney there's a small issue when I check "Loop" before previewing for the **_second_** time. Steps and video below.

We have the same behavior on the Main Branch. Should I create a new PR for this or will we fix it on this PR? Thanks!

1. Create a story
2. Add an image
3. Add an audio and the subtitles
4. Uncheck "Loop"
5. Preview - works fine
6. Close preview
7. Check "Loop"
8. Preview - that's when we have the bug, we have the audio playing twice


https://user-images.githubusercontent.com/96055551/156357319-eb0e91cb-2029-4eda-830c-b6da90c741a3.mp4

**Comment by swissspidy** [comment]
@felipebochehin87 That might be simply because the preview mode opens the story three times. Dos the audio still play twice if you click on "Open story" in the top right?

**Comment by felipebochehin87** [comment]
> @felipebochehin87 That might be simply because the preview mode opens the story three times. Dos the audio still play twice if you click on "Open story" in the top right?

Thanks @swissspidy

Yes, it does. And it happens when I publish too.


https://user-images.githubusercontent.com/96055551/156364709-2d82b9e1-5df6-4198-a8fc-1b5ba9d70e62.mp4

**Comment by felipebochehin87** [comment]
@swissspidy I'll create a new PR for the bug I mentioned. This PR looks good, and given that the bug is already in the Main branch, it means that it's not being caused by this change. Thanks for your support :) 

1. Created a story
2. Added an image
3. Added an audio and the subtitles
4. Unchecked "Loop"
5. Previewed - works fine
6. Closed preview
7. Checked "Loop" - working as expected
8. When visiting Experiments, the "Enable adding captions to background audio" option is selected by default
