### ISSUE TITLE
Sidebar: Fix positioning of popups (color/date picker, tooltips)

### ISSUE THREAD

**Issue by merapi** [swissspidy/web-stories-wp#10803]
## Feature Description

Currently, we only have color/date pickers in the right column of the editor and their positioning is not flexible (they always open on the left side of the input), so with the new Sidebar on the left side, the color picker opens out of the viewport area, I've introduced a temporary fix so the picker is at least visible but we need to change the positioning a bit. It was [discussed](https://xwp.slack.com/archives/C01ESBB8ZN1/p1645461514518299) on Slack and it should look like this:

![image](https://user-images.githubusercontent.com/21036224/157626076-231c4c06-398e-42e4-a9ad-bef427101aee.png)

Date picker case is easier, just the anchor point needs to change, right now it's top/right, should be top/left:
![image](https://user-images.githubusercontent.com/21036224/157627543-b0c5b148-9d17-41b7-a5b1-42bd6d93ad11.png)

https://github.com/GoogleForCreators/web-stories-wp/pull/10760#discussion_r818761362

PR should be based on/merged to the `sidebar` branch.

**Comment by BrittanyIRL** [comment]
@merapi - @miina flagged this for us to pick up to help you out. 

I need you to add a real description to this ticket.

**Comment by BrookeGraham** [comment]
I would love to get started on this tomorrow, but I am not sure I follow. What all is needed here?

**Comment by miina** [comment]
@BrookeGraham As far as I understand, the issue is the following:

Currently, in the `sidebar` branch, the right sidepanel was essentially moved to the left side, instead of updating all the tooltips/color picker/ date picker positions, it was just "fixed" by setting `isRTL=!isRTL`, for example: https://github.com/GoogleForCreators/web-stories-wp/pull/10760/files#diff-113a0edff03852bd3a3a51edc102345048b579c514aeed5fb9d899794f08c499R254

The goal of this issue is to remove those temporary fixes and position the popups as they actually should be, considering that the sidebar is now on the left instead.

@merapi - can you confirm?

**Comment by merapi** [comment]
> @merapi - can you confirm?

Yes, I've added a proper description that shows the correct positioning.

**Comment by BrookeGraham** [comment]
Awesome! Thanks so much y'all.

**Comment by BrookeGraham** [comment]
Would someone mind pinging me in the slack thread? (@brk) Since I was added using Slack connect, I do not have access to links that are based on XWP's slack domain.  Not a big if not. I am pretty sure I have enough context now.

**Comment by BrookeGraham** [comment]
Fixed via #10883
