### ISSUE TITLE
Performance: Page Zoom, integrate with page canvas provider

### ISSUE THREAD

**Issue by maxyinger** [swissspidy/web-stories-wp#10824]
This ticket may be a little more exploratory, but following [10730](https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/googleforcreators/web-stories-wp/10730) it would be nice to see if we can bring in the image generation action used for the page zoom into the page canvas provider, so we can share the same generated image with other components in the app (page carousel, also any contrast calculations).

this should hopefully cut down on the amount of expensive calls to generate images from story pages in the app.

**Comment by littlemilkstudio** [comment]
Turns our zoom doesn't actually generate a canvas/image, just scales up the dom nodes. Will use this ticket as an opportunity to integrate the pageCanvasProvider with the eyedropper instead

**Comment by littlemilkstudio** [comment]
Welp, the eye dropper is not hard to integrate with the page canvas cache to supply page canvas/image data, however, the existing code is tightly coupled to the size of images and nodes in the editor.

Currently it basically makes a lot of assumptions that the story page DOM node is the same pixel size as the image data we reference. With the page canvas provider it is not guaranteed that the image will be the same size as the story page DOM node.

There's definitely approaches that can be taken that use some linear interpolation to accommodate for differences in coordinate system between DOM events and the image data, but updating the logic in the eyedropper is a larger lift and out of scope for this ticket right now.

Closing this issue with this synopsis. If anyone wants to create a ticket for integrating the Page Canvas Provider into the eyedropper so that the eyedropper interacts with the page image cache, it's definitely doable, but should be marked as a 5 to accommodate for the updates needed in the eyedropper business logic.
