### ISSUE TITLE
Reduce `ELEMENT_TYPES` usage in in `story-editor`

### ISSUE THREAD

**Issue by mohdsayed** [swissspidy/web-stories-wp#10865]
## Task

As pointed out in https://github.com/GoogleForCreators/web-stories-wp/pull/10452#issuecomment-1059194243, the usage of `ELEMENT_TYPES`  in quick actions and right click menu means the story editor still has some hardcoded knowledge of what element types exist and are supported.

## Alternatives Considered

These could probably be moved to the element definition so that the element defines what menu items it has. Similar to how it defines its list of supported panels.

## Additional Context

https://github.com/GoogleForCreators/web-stories-wp/pull/10452

**Comment by swissspidy** [comment]
The new floating menu bar has the same issue:

https://github.com/GoogleForCreators/web-stories-wp/blob/a7c25387b4206ce217395fe61e9aed4e98d57065/packages/story-editor/src/components/floatingMenu/menus/selector.js#L26-L55

**Comment by swissspidy** [comment]
Related: #10863

**Comment by swissspidy** [comment]
@spacedmonkey I just realized that you opened #12938 to address this issue. Note that this issue describes the exact opposite of that PR though— we want to _remove the usage_ of `ELEMENT_TYPES` as much as possible so that the editor is not aware of the different element types.

However, this is a huge undertaking conceptually, so needs careful planning. Moving back to backlog.
