### ISSUE TITLE
Templates: Unable to create templates

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#10966]
## Bug Description

After https://github.com/GoogleForCreators/web-stories-wp/pull/10452, users are unable to create stories from a template. 

I seeing the following error in the console. 

```
Warning: Failed prop type: The prop `story.title` is marked as required in `OutputStory`, but its value is `undefined`.
    at OutputStory (http://localhost:8899/wp-content/plugins/web-stories/assets/js/packages_story-editor_src_index_js.js:161999:7)
```

## Screenshots

https://user-images.githubusercontent.com/237508/158848840-5b0e8912-cfa3-4e21-b6ac-68a0b7464526.mov

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by mohdsayed** [comment]
The warning is an existing issue. However, the bug is due to the Dashboard trying to use `elementTypes` which isn't available to it because we are registering the `elementTypes` in `StoryEditor` now in https://github.com/GoogleForCreators/web-stories-wp/pull/10452

https://github.com/GoogleForCreators/web-stories-wp/blob/7b8358691330a4257932a9cdf9fbaee2ac514fd2/packages/story-editor/src/storyEditor.js#L67-L69

When we click on the "Use template" button, it calls `createStoryFromTemplate` > `getStoryPropsToSave` > `getStoryMarkup` > `<OutputStory>` > `<OutputPage>` > `getAutoAdvanceAfter` > `getLongestMediaElement`  > `getDefinitionForType` here

https://github.com/GoogleForCreators/web-stories-wp/blob/7b8358691330a4257932a9cdf9fbaee2ac514fd2/packages/story-editor/src/output/utils/getLongestMediaElement.js#L31

and since we never registered the `elementTypes` in Dashboard, it doesn't take us to the story editor. Will think of some solution/fix.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #10972.

1. Clicked on Stories
2. Clicked on Explore Templates
3. Hovered over a template and clicked on Use template - create story screen is displayed, template is added to the story
4. Repeated steps 1 and 2
5. Hovered over a template and clicked on See details, and then clicked on Use template - create story screen is displayed, template is added to the story


https://user-images.githubusercontent.com/96055551/158901281-2c926791-beb9-4c11-ba11-a8d8f4b5961b.mp4
