### ISSUE TITLE
Floating Menu: Cannot select border color with eyedropper 

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#11024]
## Bug Description

If I select an element with a border and use the floating menu's border color to open the color popup and select the eyedropper, when I select the color I want from the canvas, that color is not applied as the border color. 

This works fine if I use the eyedropper from the color popup for the border in the style panel. 

## Expected Behaviour

Should be able to use eyedropper to select new border color in the floating menu. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by BrittanyIRL** [comment]
@felipebochehin87 I detailed testing on the PR.

**Comment by felipebochehin87** [comment]
Thanks @BrittanyIRL :)

I tested and I still get some weird behavior (testing PR #11075):

When I pick a color from the canvas using the eye dropper located on the side menu, the color is not set instantly. I need to drag and drop the element (in this case, the square) so that the border color is changed. Please see video below:

1. I select a color using the floating menu - color is set
2. I click on the eye dropper (from the Style menu) and select a color from the background or any other image - color is not set
3. I drag and drop the element - the color selected on step 2 is set

https://images.zenhubusercontent.com/235435637/45bcd9db-a838-47b3-a1e1-7cea68faceff/2022_03_28_08_35_51.mp4

**Comment by BrittanyIRL** [comment]
Thanks, Felipe! 

It looks like that's also happening in staging 😬  happy to see if I can't fix it here though. 

It might be impacting more than just borders since that seems to be outside of floating menus.

**Comment by samwhale** [comment]
@felipebochehin87 I think we fixed that! Would you mind checking this when you have some time?

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11075.

1. Added a shape
2. Added border
3. Changed color of the border using the color picker from floating menu - color changed as expected
4. Changed color of the border using the color picker from side menu (Style) - color changed as expected
5. Changed color of the border using the eye dropper from side menu (Style) - color changed as expected

https://images.zenhubusercontent.com/235435637/37592032-a8cf-418d-80ef-e6b17101a363/11024.mp4

**Comment by felipebochehin87** [comment]
@BrookeGraham @BrittanyIRL it's happening again... Should we reopen this or create a new bug?

**Comment by BrittanyIRL** [comment]
New bug. Something new is happening if this is broken again or it's a regression. Please tag me in it when you make a new ticket.
