### ISSUE TITLE
Font color won't stick on change to text preset in Firefox

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11023]
## Bug Description

Originally reported by @BrittanyIRL 
Aftering adding some text via presets, if I  update the actual text so it no longer is the placeholder text, and I try to change the font color, it doesn’t reflect the new color choice. 
![image6](https://user-images.githubusercontent.com/58738530/159565764-a68c95d7-ff5a-4754-9245-2faf7545ff91.gif)

and here
![image1](https://user-images.githubusercontent.com/58738530/159566353-500829e6-2df8-40c7-8746-a1b98a7e113c.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by barklund** [comment]
Not a bug: In both the above videos, the text field is in edit mode, nothing is selected, and nothing is typed after changing color. No color change is then expected. Changing text color can have three different outcomes:

1. If not in edit mode, the entire text field changes to the desired color:
![no-edit](https://user-images.githubusercontent.com/637548/174810328-4bff7817-ce64-431a-b670-de20a1dfd0fe.gif)

2. If in edit mode with selection, selected text changed color:
![edit-selection](https://user-images.githubusercontent.com/637548/174810895-00ac3d06-10ee-4e0e-8878-2f3cb3d026bb.gif)

3. If in edit mode with no selection, nothing immediately changes color, but text typed after color change will have new color (note that this is a bit tricky to do, because keyboard focus does not naturally return to the text field after color change):
![edit-no-selection](https://user-images.githubusercontent.com/637548/174811461-11ee5d12-89b2-4d28-8d88-2bb66ff78163.gif)

Also note that none of this is specific to font color. All of the other inline font styles work this way including font weight, letter spacing, font variant (italics), and text decoration (underline).

We can change case 3 in the above list to mean the same as case 1, but that is a design choice, not a bug.
