### ISSUE TITLE
Background Audio: Audio always loops when playing in the editor

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11046]
## Bug Description

Originally reported by @BrookeGraham 
 in the design panel, if I uncheck the loop box, then hit the play button, the audio still loops until I hit the stop button. The loop checkbox does not impact the preview functionality as one would expect

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Looks like the issue is with the `AudioPlayer` in the editor always looping:

https://github.com/GoogleForCreators/web-stories-wp/blob/e36bd696131081f5b03135789b7a216e5e013486/packages/story-editor/src/components/audioPlayer/index.js#L101

We should pass the `loop` value as a prop here:

https://github.com/GoogleForCreators/web-stories-wp/blob/e36bd696131081f5b03135789b7a216e5e013486/packages/story-editor/src/components/panels/shared/backgroundAudioPanelContent.js#L204-L212

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #11067.

1. Added an audio file to the background
2. Checked "Loop" checkbox
3. Clicked on play - audio plays over and over (looping)
4. Stopped preview
5. Unchecked "Loop" checkbox
6. Clicked on play - audio stops once its execution ends (no loop)
7. Tested checking and unchecking the checkbox while audio is playing (during audio execution) - working as expected

https://images.zenhubusercontent.com/235435637/7585264e-d1b9-42fe-b916-bdd9180c62dc/11046.mp4
