### ISSUE TITLE
Shape's floating menu color picker presents extra tooltip in old Safari

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11043]
## Bug Description
Originally reported by @samwhale 

Using the floating menu bar's color picker for a shape triggers the display of two tooltips at the same time

![image8](https://user-images.githubusercontent.com/58738530/159694064-59c6dd20-5688-421e-bbbd-99cff58a5657.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by BrookeGraham** [comment]
Hi @merapi I was able to fix this with #11280

**Comment by BrookeGraham** [comment]
@felipebochehin87 you can use #11280 to check this.

**Comment by felipebochehin87** [comment]
@BrookeGraham I still see this bug on Safari. However, the other bugs that are fixed in 11280 (on Firefox, for example) are good.

Tested on Safari 15.4 (17613.1.17.1.13), MacBook Pro (16-inch, 2019, macOS Monterey 12.3.1)

[Uploading... Screen Recording 2022-04-20 at 08.36.47.mov]

**Comment by felipebochehin87** [comment]
[Uploading... Screen Recording 2022-04-20 at 08.36.47.mov]

**Comment by felipebochehin87** [comment]
[https://app.zenhub.com/files/235435637/2bb19357-c94f-4306-8965-d13ad0cbb0ed/download](https://app.zenhub.com/files/235435637/2bb19357-c94f-4306-8965-d13ad0cbb0ed/download)

**Comment by BrookeGraham** [comment]
Dang. So in Safari we are dealing with some focusing issue within the color picker and the floating menu. That means #11280 will not fix this issue. 😢

**Comment by BrookeGraham** [comment]
My bad, didn't mean to close it when I merged in #11280

**Comment by BrookeGraham** [comment]
This issue stems from a much larger bug in Safari itself. In Safari, when you click on a button / input it does not automatically received focus, focus is moved to the parent div. This means accessibility going from keyboard to mouse interactions throughout the app is currently broken in Safari. For example if you are focused in the Sidebar tabbing through it and then you click on the show keyboard shortcuts icon, then toggle it closed still with the mouse, if you try to use the keyboard to tab, you will not be focused on the keyboard icon. If we want to make keyboard to mouse back to keyboard in sync in Safari, we need to properly scope out that work and it should be its own epic since there may be many places where this would need to be addressed. 

@littlemilkstudio was kind enough to draft up a [code sandbox](https://codesandbox.io/s/purple-microservice-hkoo0c?file=/src/App.js) to demonstrate this. 
Open in Safari, open dev tools. 
Click the button.  
In dev tools you'll see what has focus, note that the button doesn't. 


See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#clicking_and_focus
Also See: https://bugs.webkit.org/show_bug.cgi?id=22261

**Comment by BrookeGraham** [comment]
To address the `Tooltip` getting shown because of this, we decided to add a delay to all the tooltips that are in the floating menu. It doesn't solve the problem, but does make it much less noticeable in Safari. I will put up the pr today.

**Comment by littlemilkstudio** [comment]
I think it's important to note that most users will be navigating with keyboard **or** mouse, not both. It will be an even smaller percent of users that navigate interchangeably between keyboard and mouse, and use safari. Probably not an issue we should focus on.
