### ISSUE TITLE
Dashboard won't show second page of stories for a contributor

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11054]
## Bug Description

Originally reported by @BrittanyIRL 

> I’m logged in at a contributor level, on the dashboard the second page of stories won’t load under “all stories” - totally fine for pending and published no matter how many pages to go get. Maybe it’s because I logged in as admin and then switched users? Maybe what’s happening here is in line with the “all stories” WP view? Where at the contributor level the initial view of stories is “mine” - however in the dashboard we’re asking for all of them and so the surrounding state of the dashboard thinks there is more to load (there is for all) but for just “mine” there’s nothing else so we get the loading spinner which is out of sync. So we either need a “mine” setting for that role or fix whatever changed in the request. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
This reminds me of #8532 / #8976 and specifically https://github.com/GoogleForCreators/web-stories-wp/issues/8532#issuecomment-907217461 which explains what's going on. So this report is pretty much a duplicate I'd say.

Basically, the dashboard requests 24 stories from the WP REST API. WP then fetches 24 stories from the database and filters out all the ones you don't have access to.

Contributor users only have access to their own stories or already published ones.

That means when requesting 24 stories you might only get returned a handful. Even though the count says something different.

**Important:** The WP REST API by design shows less information than what you see on the "All Stories" page. On "All Stories", you can still see the titles of stories you don't have access to, but the REST API does not even return them. That's why we can never really get the dashboard to match the "All Stories" page.

Here's an example to demonstrate this:

![Screenshot 2022-03-23 at 16 20 26](https://user-images.githubusercontent.com/841956/159740544-fcf27227-5fe0-4365-856a-3e866370b2bd.png)
![Screenshot 2022-03-23 at 16 21 30](https://user-images.githubusercontent.com/841956/159741507-1eefa23d-39b2-4f38-8430-009b4c6524da.png)

Stories (1), (2), (3), and (4) are either created by the Contributor user or published. All others are not returned in the REST API.

Hence the discrepancy.

For these reasons I'd say this is a duplicate of the aforementioned tickets and basically a wontfix from our side. Or at least a super low prio ticket to look into.

Aside: Adding a "Mine" tab would not solve this issue, but would be a nice enhancement that can be tracked separately.

cc @spacedmonkey

**Comment by spacedmonkey** [comment]
I don't have much to add here. But Pascal is right. I don't that we can fix this issue.

One work around would be up the number of stories requested to say 100. This means that you are more likely to see story you have access and pagination happens less. But I am not sure we if want to do this.

**Comment by BrittanyIRL** [comment]
Felt like that to me too but I thought we'd fixed it so assumed this was a regression. How many instances are there of people using this as a contributor? Has anyone noticed this being an issue?

**Comment by swissspidy** [comment]
> How many instances are there of people using this as a contributor? Has anyone noticed this being an issue?

According to analytics, very very very few. The vast majority is administrators. I don't recall any support requests for this either.

But of course I noticed it too, hence my screenshots above :)
