### ISSUE TITLE
Taxonomy Panel: Color Accessibility 

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#11071]
Looks like the taxonomy panel needs to have its color contrast updated: https://github.com/GoogleForCreators/web-stories-wp/runs/5634144887?check_suite_focus=true#step:7:703 

Let's sync with design on a path forward to meeting WCAG since these colors are from the design system we need to be careful and attentive to solving the issue holistically - as aXe might be flagging them in taxonomy but it's probably present elsewhere. 

@BrittanyIRL to prep colors ahead of next design sync and touch base with @agingoldseco

**Comment by swissspidy** [comment]
Just looking at the errors again and it's odd that the background color is `#ffffff` for all of these reported errors—which clearly can't be right since the sidebar is gray.

So maybe it's not an actual design issue, just an issue with the aXe test.

Can you perhaps double check that before looping in UX? Thanks!

**Comment by swissspidy** [comment]
Thanks for looking into it!

There were some contrast updates in https://github.com/dequelabs/axe-core/releases/tag/v4.4.0, so maybe something regressed there 🤷  But strange that nothing is reported in DevTools.

I think for now it's just easiest to disable the rule for that particular test. I'll try that in #11005 real quick.
