### ISSUE TITLE
Audio Capture: Initial implementation

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11079]
## Feature Description

Enable support for audio-only recording, uploading the audio clip to WordPress and then setting it as page background audio.

**[Figma](https://www.figma.com/file/ZrO763yvMWJjYeAPsRnNfW/_Editor---Sprint-Feature-Level-Designs_2022?node-id=661%3A24394)**

While there are no designs for this yet, I'd imagine the flow to be somewhat like this:

1. When opening the media recording mode, by default we'll turn on the webcam and microphone. You see yourself on the canvas.
2. In the quick actions menu you can then disable either the camera or mic (but not both).
3. When you turn off the camera, instead of seeing yourself on the canvas we display an equalizer to visualize the sound
4. When you start recording, you continue to see the visualization
5. When you stop recording, we display a simple audio player to play/pause the audio
6. There is an "Insert background audio" button at the bottom
7. When you click on the button, we:
	1. Upload the audio file to WordPress via `uploadFile` from `useUploader`
	2. Take the resulting file URL and add it as page background audio
	3. Use `setHighlights` from `useHighlights` to focus the page background audio panel in the "Style" tab, so that the user knows where the audio file was added

## Additional Context

* `Stories_Media_Controller` needs updating to allow uploading audio files to WP

**Comment by felipebochehin87** [comment]
Errors when trying to upload video and audio. Please check the error details in the attached filed (txt).

OK - When opening the media recording mode, by default we'll turn on the webcam and microphone. You see yourself on the canvas.
OK - In the quick actions menu you can then disable either the camera or mic (but not both).
OK - When you turn off the camera, instead of seeing yourself on the canvas we display an equalizer to visualize the sound
OK - When you start recording, you continue to see the visualization
OK - When you stop recording, we display a simple audio player to play/pause the audio
OK - There is an "Insert background audio" button at the bottom
**NOK** - Upload the audio file to WordPress via uploadFile from useUploader
**NOK** - Take the resulting file URL and add it as page background audio
**NOK** - Use setHighlights from useHighlights to focus the page background audio panel in the "Style" tab, so that the user knows where the audio file was added

![image (11).png](https://images.zenhubusercontent.com/61d5f112aca19e2c5bb2441f/8671a431-8dd6-421e-b747-2b880c9bc626)

[https://app.zenhub.com/files/235435637/07afc4da-f520-4c43-af69-147d8c0712a2/download](https://app.zenhub.com/files/235435637/07afc4da-f520-4c43-af69-147d8c0712a2/download)

**Comment by felipebochehin87** [comment]
[Uploading... 2022_07_13_19_28_39.mp4]

**Comment by merapi** [comment]
Thanks for testing @felipebochehin87.
Since this error is related to FFmpeg which is used already in other places and we don't have any bug reports on this, we will treat it as a very rare case and monitor it. I can't reproduce it on any of my Windows/Chrome machines.

**Comment by swissspidy** [comment]
Also worth noting that the above is related to video recording, whereas this ticket is about audio-only recording.
