### ISSUE TITLE
Story Editor add image as background issue 

### ISSUE THREAD

**Issue by santoshgistto** [swissspidy/web-stories-wp#11118]
When we click on image to add as background to story card, its working as expected. 
Please check below video
Branch : `main`
 
https://user-images.githubusercontent.com/12577046/160713275-67c38d23-b353-46df-aa7b-b97a904666df.mov

**Comment by LuckynaSan** [comment]
@santoshgistto Hello, thank you for your report. Please be advised that Web Stories support is provided over in the [WordPress Support Forum](https://wordpress.org/support/plugin/web-stories/) but since you are already here we can troubleshoot further on this ticket. 

Please share the following details:

- Who is your hosting provider?

- If possible, could you check if this issue occurs when Web Stories is the only plugin enabled and when using a default theme? You can safely simulate this by using the [Health Check & Troubleshooting plugin](https://wordpress.org/plugins/health-check/).

- Could you please open your dev tools and check for any browser console errors?

**Comment by santoshgistto** [comment]
Thanks @LuckynaSan  for response.
Actually i am using the editor in react app. 
We could close this ticket if it is not applicable.

**Comment by swissspidy** [comment]
Ah so you're using the standalone decoupled editor via our npm packages. It would be great to mention that from the beginning by filling out the issue template :-)

I am currently unable to reproduce this in our [editor storybook](https://googleforcreators.github.io/web-stories-wp/storybook/?path=/story/playground-stories-editor--default). Does it work for you there?

**Comment by santoshgistto** [comment]
@swissspidy  sorry for not filling the template i will do that next time if any issue occurs.  :) 
Yes it works on storybook. 
But in previous version no issue in v1.17.0 i believe  
is any style is missing ?

**Comment by santoshgistto** [comment]
@swissspidy Any pointer for this would helpful to check whats going on in stand alone case

**Comment by santoshgistto** [comment]
my bad added html template `<script src="https://cdn.tailwindcss.com"></script>` was causing the issue 
🤦 
Thank you

**Comment by santoshgistto** [comment]
The reason is `@tailwind base` has  ` max-width:100%`
```img,
video {
  max-width: 100%;
  height: auto;
}```

Link : https://unpkg.com/tailwindcss@3.0.23/src/css/preflight.css
