### ISSUE TITLE
Design System: Dropdown Popup

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#11202]
## Feature Description

Creating a DropdownPopup will decrease the variety of general Popup usage. The Dropdown Search and DataList all have very similar use cases, feature, and overall feel for the Popup.

**Comment by BrookeGraham** [comment]
After pulling out the `Tooltip` and simplifying the `Popup`, I no longer think we need to separate out `Dropdown`. It can continue to use the Popup component since there isn't much differentiation here. I am gonna use this ticket to clean up the `Dropdown` and `Popup` component so we are no longer sending down needless props.
