### ISSUE TITLE
Errors rendering Editor in Next.js

### ISSUE THREAD

**Issue by mohdsayed** [swissspidy/web-stories-wp#11219]
## Bug Description

I was trying to create Story Editor in Next.js however there were several errors that appear one after the other ( Most of them are due to Next.js SSR )

![image](https://user-images.githubusercontent.com/6297436/162434867-98019d14-0358-4735-85cc-588c79e89f4c.png)

( Gets fixed by removing [CSS import ](https://github.com/GoogleForCreators/web-stories-wp/blob/afe02f9209112c2447559dbfa797e3192b052f96/packages/story-editor/src/components/form/dateTime/datePicker.js#L20) )
Reference: https://nextjs.org/docs/messages/css-npm

![image](https://user-images.githubusercontent.com/6297436/162434888-171977b7-fcaf-4493-b14a-bf3fce44ede6.png)

( Gets fixed by using `globalThis` )

![image](https://user-images.githubusercontent.com/6297436/162434900-823f53ed-bb9b-406b-bd5b-646db4a4c983.png)

( Gets fixed by removing `"type": "module"` from `package.json` )

![image](https://user-images.githubusercontent.com/6297436/162435236-a277536b-a6ef-4d4c-90c6-372ad78abddf.png)

![image](https://user-images.githubusercontent.com/6297436/162435250-37c1e570-07b4-435f-adec-51319d37da25.png)

![image](https://user-images.githubusercontent.com/6297436/162435266-37c8cb2d-47fb-4d3d-8509-d6330c84cece.png)

![image](https://user-images.githubusercontent.com/6297436/162435283-b3584b13-32f0-4c42-8ece-7659cc934f49.png)

![image](https://user-images.githubusercontent.com/6297436/162435305-974175bb-5043-462a-92f2-2cd4e7df9ff8.png)

![image](https://user-images.githubusercontent.com/6297436/162435315-25f32833-8b04-477a-91f0-3372de153e16.png)

## Expected Behaviour

Editor and dashboard should work without any issues in NextJs.

## Steps to Reproduce

Step - 1: `npx create-next-app@latest`

Step - 2: Use snippet from [getting-started](https://github.com/GoogleForCreators/web-stories-wp/blob/main/docs/third-party-integration/story-editor/getting-started.md#step-3-use-the-storyeditor-component-to-render-the-editor) to use the editor

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by sayedtaqui** [comment]
Regarding this

![image](https://user-images.githubusercontent.com/6297436/163184678-fd49825e-8ddb-470b-b1b4-f4161d0bbe6d.png)


> ( Gets fixed by removing [CSS import ](https://github.com/GoogleForCreators/web-stories-wp/blob/afe02f9209112c2447559dbfa797e3192b052f96/packages/story-editor/src/components/form/dateTime/datePicker.js#L20)and copying it in package)
Reference: https://nextjs.org/docs/messages/css-npm

Even if the CSS is copied to the `dist`/`dist-module` folder by the rollup plugin and it references the import from a local file, it would still not work because the [doc says](https://nextjs.org/docs/messages/css-npm) that it will error if 

> One of your dependencies (node_modules) imports a CSS file

So basically Next.js is expecting us to export a compiled version of the CSS from `story-editor` which can directly be imported there.

I can think of only two solutions

1. We remove the `react-calendar/dist/Calendar.css` import from [dataPicker.js](https://github.com/GoogleForCreators/web-stories-wp/blob/1674df7a2c2321c8bee392a5ed0bb273c0f634ab/packages/story-editor/src/components/form/dateTime/datePicker.js#L20) and import it somewhere in `wp-story-editor` maybe in `packages/wp-story-editor/src/components/documentPane/publish/publishTime.js` because the core story-editor doesn't use the date picker by default unless you set up the document tab from the integration package. Then only if somebody is integrating the full editor in Next.js, they can import `react-calendar/dist/Calendar.css` directly in their component as we did for `wp-story-editor`. It doesn't look like an ideal solution though.

2. Anyone integrating the editor in Next.js uses a workaround by adding [next-transpile-modules](https://www.npmjs.com/package/next-transpile-modules) npm package and configuring in their `next.config.js` like this
```js
const withTM = require('next-transpile-modules')(['@googleforcreators/story-editor']);
const nextConfig = withTM({
  reactStrictMode: true,
  compiler: {
    styledComponents: true,
  },
})
```
That would fix the problem without us making any changes to our codebase.

Since a workaround is available for making it work for Next.js, maybe we can think of some better solutions later.

**Comment by swissspidy** [comment]
I somehow naively added `rollup-plugin-import-css` that was supposed to handle CSS imports and turning them into JS modules, but it doesn't appear to be working at all. Like, it does not do anything.

I don't mind making any code changes, since this is only really because of 1 CSS file that is only needed because we have never fixed #1391. Solving that ticket would remove this CSS file anyway.

So my proposed solution (3) would be to:

1. Turn this CSS file into styled-components definitions
2. Remove the CSS import
3. Update webpack config so that `MiniCssExtractPlugin` & co. only work for other packages, so that we never accidentally re-introduce CSS imports in `story-editor` in the future.

**Comment by sayedtaqui** [comment]
Great, I didn't know we have a ticket for it. So if we would never want to import CSS in the core packages, this would work.

> Update webpack config so that MiniCssExtractPlugin & co. only work for other packages, so that we never accidentally re-introduce CSS imports in story-editor in the future.

I do not know how we can change the configuration only for `story-editor`/`dashboard` in Webpack when the `entry` is from `wp-*` packages for `editorAndDashboard` config.

So I added an eslint rule to prevent this from happening in #11264

**Comment by swissspidy** [comment]
Ah right, yeah that makes sense. Because we import CSS files in `wp-story-editor` and `wp-dashboard` that wouldn't work. An ESLint rule is a great idea 👍

**Comment by sayedtaqui** [comment]
Just adding a note here for reference.

We can ignore `document`/`window`/`self` or similar things if:
- They are used inside `useEffect`/`useLayoutEffect` hooks because they are not called during SSR.
- They are called inside a callback or internal function which are not directly called during rendering.
- They are inside `try/catch`

**Comment by swissspidy** [comment]
This is being worked on in #11270.
