### ISSUE TITLE
Code Quality: Undefined panel type for shape element

### ISSUE THREAD

**Issue by mohdsayed** [swissspidy/web-stories-wp#11257]
## Bug Description

One of the values of `panels` array is not defined here
https://github.com/GoogleForCreators/web-stories-wp/blob/7722b81051310337bfd0cb186f14a21a143438e6/packages/element-library/src/shape/constants.js#L51

https://github.com/GoogleForCreators/web-stories-wp/blob/7722b81051310337bfd0cb186f14a21a143438e6/packages/design-system/src/utils/panelTypes.js#L34-L51

<img width="216" alt="image" src="https://user-images.githubusercontent.com/6297436/163029800-93369ea5-8399-4efb-858b-2500f7fa071f.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Surprised this went unnoticed for so long, though glad that it doesn't seem to cause any fatals.
I guess with TypeScript we would have caught this.

Not sure if this was supposed to be implemented eventually or actually removed at some point. But I assume we could just remove it now, since it doesn't seem to bother anyone.

@barklund perhaps you have more context here?

**Comment by swissspidy** [comment]
Fixed by #12929
