### ISSUE TITLE
Prefilled Web Stories block causes block validation error

### ISSUE THREAD

**Issue by fellyph** [swissspidy/web-stories-wp#11281]
## Bug Description

I have noticed this issue twice, when I published my webstory, a pop-up will suggest creating a new post, when I click on add the block with the story will be invalid.

![Screen Shot 2022-04-17 at 09 51 18](https://user-images.githubusercontent.com/330792/163708074-4ca46a90-7669-4981-9b2e-0ea7178bbb80.png)

## Expected Behaviour

When the user includes a new post the story block should be valid.

## Steps to Reproduce

1. publish a new webstory
2. click on add a new post 
3. open the post with the story block

## Screenshots

block with error:
![Screen Shot 2022-04-17 at 09 51 32](https://user-images.githubusercontent.com/330792/163708054-20f1d82e-4620-45d9-9a1e-9a26365a2282.png)

Console error:
![Screen Shot 2022-04-17 at 09 51 57](https://user-images.githubusercontent.com/330792/163708032-02c86aac-19d4-4efa-a3a7-ffb2f2adf95d.png)

## Additional Context

- Plugin Version: 1.19.0
- WordPress Version: 5.9.3
- Operating System: macOS
- Browser: Chrome 100

**Comment by swissspidy** [comment]
Thanks for your report! We‘ll look into this right away

**Comment by swissspidy** [comment]
Looks like this is because the `\Google\Web_Stories\Admin\Admin::prefill_post_content()` method uses the `Image` renderer to generate the simple `<img>` markup for the story poster. That image markup can contain `srcset` and `sizes` attributes.

https://github.com/GoogleForCreators/web-stories-wp/blob/2c2ecc275a849167398634f6080280bcf2b9f92b/includes/Admin/Admin.php#L161-L176

But the Web Stories block `save()` function does not add these attributes:

https://github.com/GoogleForCreators/web-stories-wp/blob/2c2ecc275a849167398634f6080280bcf2b9f92b/packages/stories-block/src/block/save.js#L42-L52

This causes the block validation error.

We need to update `\Google\Web_Stories\Admin\Admin::prefill_post_content()` to not render an `<img>` tag with `srcset` and `sizes`.

This could be achieved by not using the `Image` renderer and instead assembling the markup manually. Alternatively, somehow trick the `Story` model into not adding image sub sizes. Or add an option to the renderer for this (though that seems odd).

**Note:** every time we'd make a change to `Image` without also checking `save()` this could theoretically happen. We need to make our existing e2e test here more robust to prevent such regressions in the future.
As long as we do this, the chosen method does not matter too much.

cc @spacedmonkey
