### ISSUE TITLE
Give developers the option to disable Google fonts for Web Stories

### ISSUE THREAD

**Issue by adamdunnage** [swissspidy/web-stories-wp#11305]
## Feature Description

As raised in the [support forum](https://wordpress.org/support/topic/disable-google-fonts-with-snippet/#post-15568062), it would be useful for some users of the plugin to be able to disable Google fonts for their Web Stories. 

This could be provided in the form of documentation for developers who should be made aware that this be carried out at their own risk. 

Adding a UI option for this would be considered high risk for users as it could potentially break templates and existing stories so adding this as documentation for developers is the preferred approach.

## Alternatives Considered

N/A

## Additional Context

Support forum topic : https://wordpress.org/support/topic/disable-google-fonts-with-snippet/#post-15568062

**Comment by key6** [comment]
how can disable google fonts?

**Comment by swissspidy** [comment]
@key6 Right now there is no such way, as many of the built-in templates rely on Google Fonts, which makes this difficult to implement. However, it's possible to upload custom fonts on the settings page and just use those custom fonts in your story. Then you won't be using Google Fonts.

**Comment by netropol** [comment]
Due to GDPR reasons, I need to host Google fonts locally. I've tried to add several Google fonts using the Custom Fonts option in the settings, but it won't allow me because it states that: "A font named PT Sans already exists."
The same happens with fonts like Fjalla One.
I haven't created any stories nor have I previously added these fonts.
How can I successfully add Google fonts locally?

**Comment by swissspidy** [comment]
@netropol We don't have any error messages with wording like this. This doesn't sound like you are perhaps trying to upload fonts in the Font Library in 6.5, which is something else. The Web Stories plugin allows adding custom font files under Stories -> Settings -> Custom Fonts. You need to enter the URL to a font file.

**Comment by netropol** [comment]
Hi @swissspidy
Thanks for your quick response.
What I am doing is exactly that. In Stories -> Settings -> Custom Fonts, I add the URL of a Google font and the result is a red error message: A font with the name already exists...
I just did a test with the font roboto-v30-latin-regular.woff which I uploaded to my hosting, added the URL in Custom Fonts, and again got the message that a font with the name Roboto already exists.

**Comment by swissspidy** [comment]
Oooh, I see! Now I get it. Alright, I just opened #13621 to look into this. We'll need to make some changes to support that use case.

**Comment by netropol** [comment]
Thanks @swissspidy for addressing this so quickly. Looking forward to the update!

**Comment by swissspidy** [comment]
@netropol So we looked into this and it turns out making that work (custom fonts overriding Google Fonts) is actually a bit more complex than what we have thought.

To achieve what you want (serving fonts locally without loading from Google Fonts), we can however recommend the following plugin: https://wordpress.org/plugins/easyfonts/

Once enabled, it will automatically download all the fonts it found in stories and serve them from your own site.

**Comment by netropol** [comment]
Thank you for recommending the plugin @swissspidy. I haven't tried it yet, but if it works as you mentioned, I believe it will help me serve the fonts as required by GDPR.
