### ISSUE TITLE
Multiple Errors Coming From Web Stories

### ISSUE THREAD

**Issue by emilrueh** [swissspidy/web-stories-wp#11306]
Hi Web Stories Dev-team,

We have tried getting responses in the wordpress forum but they threatened to ban us because we included Pascal’s @ name in the post and told us that they do not help out for web stories with big errors and we should delete your plugin and find an alternative. After creating 110 web stories and countless months creating them, that is not an option for us and if I was you I would be very upset at moderation agents for your plugin telling users in your wordpress forum support to delete your plugin. From now on sadly we are going to have to use github due to the shocking support we are getting from how the forum is set up to help wordpress users designed to get assistance.

I have gone through the whole of the website using different pages using right click inspect and then seeing what the errors are. The only errors I can find are coming from your plugin and I have zero other errors showing from other plugins that may be causing the conflict so I am at a loss on how to fix it. Below is a list of the errors I am hoping that you will help us with and that you won't tell us to delete your plugin and start again with a new one like the wordpress support did.

## Bug Description

1. Music Not Consistently Playing

It does not happen all the time, just most of the time, but the music does not start playing for ages. Please see example below as the music track does not play for long time but the voice over kicks in when it should

https://nonfungibleownership.com/web-stories/murall-paint/

2. Errors showing on our page types

The following error is being shown on the below page

https://nonfungibleownership.com/nft-collectibles-tokens/

GET https://nonfungibleownership.com/wp-content/plugins/web-stories/assets/css/269b283795a3f40f98b2.svg 404

3. Errors showing on our buy pages

The following error is being shown on the below page

https://nonfungibleownership.com/currencies/GHST/aavegotchi/

xhr-impl.js:75          GET https://nonfungibleownership-com.cdn.ampproject.org/mbv/s/nonfungibleownership.com/wp-content/uploads/RJ-27.mp3?amp_video_host_url=https%3A%2F%2Fnonfungibleownership.com%2Fweb-stories%2Faavegotchi-ghst-review%2F&__amp_source_origin=https%3A%2F%2Fnonfungibleownership.com 404

4. Errors showing on the actual web stories

The below errors are showing when we click on a web story - see example https://nonfungibleownership.com/currencies/GHST/aavegotchi/

amp-story.js:1157 Uncaught TypeError: Cannot read properties of null (reading 'next')
    at As.pe (amp-story.js:1157:12)
    at As.Vst (amp-story.js:1239:12)
    at amp-story.js:651:12
    at page-advancement.js:200:7
    at Array.forEach (<anonymous>)
    at Ko.onTapNavigation (page-advancement.js:199:34)
    at Ko.pit (page-advancement.js:698:10)
pe @ amp-story.js:1157
Vst @ amp-story.js:1239
(anonymous) @ amp-story.js:651
(anonymous) @ page-advancement.js:200
onTapNavigation @ page-advancement.js:199
pit @ page-advancement.js:698
index.js:43 Uncaught (in promise) Error: No messaging channel: initMessagingChannel timeout
    at l (index.js:43:13)
    at _t.createError (log.js:295:45)
    at timer-impl.js:130:23
    at timer-impl.js:71:9
l @ index.js:43
createError @ log.js:295
(anonymous) @ timer-impl.js:130
(anonymous) @ timer-impl.js:71
Promise.then (async)
coreServicesAvailable @ performance-impl.js:333
(anonymous) @ amp.js:55
Ci @ chunk.js:190
ji @ chunk.js:409
(anonymous) @ chunk.js:322
postMessage (async)
Qi @ chunk.js:514
Wi @ chunk.js:503
Ki @ chunk.js:368
runForStartup @ chunk.js:357
Un @ chunk.js:59
nu @ amp.js:50
(anonymous) @ amp.js:130
Ci @ chunk.js:190
ji @ chunk.js:409
(anonymous) @ chunk.js:322
postMessage (async)
Qi @ chunk.js:514
Wi @ chunk.js:503
Ki @ chunk.js:368
runForStartup @ chunk.js:357
Un @ chunk.js:59
(anonymous) @ amp.js:117
(anonymous) @ version.js:11

5. The AMP Story validation tool shows an error message asking to please try again later after putting in any story urls into the tool bar

## Screenshots

![amp issue ws](https://user-images.githubusercontent.com/103951556/163970942-b68dd91b-7439-4809-adcc-cda9830ce4b4.PNG)

## Additional Context

- Plugin Version: 1.19.0
- WordPress Version: 5.9.3
- Operating System: Windows 10
- Browser: Opera and Chrome

**Comment by swissspidy** [comment]
Hi Emil

I am sorry to hear that you continue running into issues related to stories and we try our best to help all our users as much as possible. Of course sometimes our options for that are limited, i.e. if there are things that outside the scope of our support offering. Speaking of support offering, we generally do not provide support via GitHub, but only via WordPress.org.
Also, I hope you do understand that WordPress.org forums moderators are following and enforcing the [forum guidelines](https://wordpress.org/support/guidelines/). The guidelines cover things like bumping posts and abusing `@<name>` mentions trying to get assistance faster.

Now, while you are already here, I try to go through the errors that you mentioned here one by one to give you pointers on how to resolve them.

> 1. Music Not Consistently Playing

At first glance, your story with the background audio looks alright and I don't see any problems there from a setup/content perspective. That means this would be an issue with the Web Stories format itself, so our hands here are tied.

I kindly ask you to report this at https://github.com/ampproject/amphtml where the team developing this format can dig deeper into solving this one.

> 2. Errors showing on our page types

This is a bug that we have already identified and fixed. This will be fixed in our next release (due out next week).

No action needed from your side.

> 3. Errors showing on our buy pages

While I can't replicate this issue right now, these types of 404s usually simply mean that some content could not be loaded from the AMP cache (for example because the content is still rather new and not added to the cache yet).

There's nothing concerning about this so you can simply ignore this informational message.

> 4. Errors showing on the actual web stories

While I can't replicate this issue right now, this would again be an issue with the Web Stories format itself.

Please report this at https://github.com/ampproject/amphtml, providing the same error message and as much additional information as possible. This way the team developing the format can take a look at it.

> 5. The AMP Story validation tool shows an error message asking to please try again later after putting in any story urls into the tool bar

The WordPress plugin team does not maintain the validation tool so unfortunately there's not much we can do about this for you.

I recommend you to check whether there's anything on your server (i.e. security measures) blocking the tool from accessing your site. Also use the Help/Feedback options provided on the tool itself.

**Comment by emilrueh** [comment]
Hi Pascal, thanks for your in-depth reply to the issues, we will go through them and let you know.
About the forum guidelines regarding tagging people it states the following so was sure tagging you would be an option we are allowed to use, surely this is not your problem or field but just to explain ourselves.

> Public links in plugin or theme support topics may only be posted if they meet one or more of the following criteria:
> 
> The link is to the plugin or theme authors own website.
> The link is to the plugin or theme authors own support website.
> The link is posted by the plugin or theme author them selves to an external resource related to the topic.
> The link is to resources on the WordPress.org website.
> The link is to a reputable image-sharing service for screenshots.

**I do have a further question:**
How to properly add a single story to a wp post or page sidebar to have display the poster image or story itself including a button that redirects to the story url?
Before we did this via a now broken shortcode widget. Do you have an in-house option for that?

**I would also like to add a feature request:**
Will there be an option to have stories of certain categories or tags displayed together via widgets or carousels?
Right now there is just the options for ascending and descending date or title.
An option for single stories would be great, and option for certain categories as well.

**Comment by swissspidy** [comment]
> How to properly add a single story to a wp post or page sidebar to have display the poster image or story itself including a button that redirects to the story url?

Right now we don't support this, but we have an open feature request (#6894) to allow displaying a single story with a poster image & opening the full story in a lightbox upon click.

> Will there be an option to have stories of certain categories or tags displayed together via widgets or carousels?

This is also an open feature request (#8897) on our side. Unfortunately I don't have an estimate for you on when this will be implemented. But it's on our radar.

**Comment by emilrueh** [comment]
Good to hear you have things on the radar. Going through the points you mentioned. Thank you, may come back later.
