### ISSUE TITLE
Web Stories carousel not using cropped thumbnails

### ISSUE THREAD

**Issue by fellyph** [swissspidy/web-stories-wp#11307]
## Feature Description

I have implemented the Web Stories listing on the header, and my score at the core web vitals has decreased because the thumbnails loaded for my web stories are 640px for a thumbnail with 80x80px, It would be good if the thumbnails load a close image size, a thumbnail crop, for example, to avoid load large images in a small container.

**list example:**

![Screen Shot 2022-04-19 at 09 44 09](https://user-images.githubusercontent.com/330792/163983665-fc14536d-bc85-4f1c-a898-bbac0a344b23.png)

**Page speed test:**

![Screen Shot 2022-04-19 at 08 40 30](https://user-images.githubusercontent.com/330792/163983688-deee6d2f-2f22-4ae8-b12d-c92f42de4f46.png)

## Additional Context

- I'm using the AMP plugin with standard mode.

**Comment by swissspidy** [comment]
Hi Fellyph

Thanks for raising this.

The presence of the `sizes` and `srcset` attributes indicates that there are simply no smaller suitable sizes available. Which is somewhat expected, because there is unlikely to be a smaller image size with the same aspect ratio. Also, we have previously removed square crops as it often times caused confusion and even bad results (not to mention the additional storage needed).

Related:

* #5080
* #4764
* #7983
* #7849

We'll take some time to think a bit about good solutions here.
