### ISSUE TITLE
Checklist: No Animation on First Page

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#11320]
## Feature Description

AMP doesn't allow animation on the first page of a Story. Currently, users can add animations to the first page of a Story in the editor. We want to acknowledge the animations so we're not stripping them from the first page (page order can change). It would be helpful for a user to know why the animation isn't playing and that it's not a bug (see https://github.com/GoogleForCreators/web-stories-wp/issues/9987).

This ticket is to add an issue to the checklist under the design panel telling the user that their animation won't play on the first page. It'll look something like the below (work with @swissspidy for proper verbiage and where (if present) the "Learn more" link should go). 

## Additional Context

This will be a single action no CTA checklist card variant. You can see all the checklist card variants in storybook (run `npm run storybook` and then go to story editor components checklistCard. It will look something like this: 
<img width="291" alt="Screen Shot 2022-04-20 at 11 07 10 AM" src="https://user-images.githubusercontent.com/10720454/164294837-8e2dbf80-bba5-431c-8718-54caf94105aa.png">

```
  <ChecklistCard
          title="First Page Animations"
          footer={
            <DefaultFooterText>
              {'Animations are prevents on the first page of Stories to help with performance. '}
              <Link
                href="/demo"
                size={THEME_CONSTANTS.TYPOGRAPHY.PRESET_SIZES.X_SMALL}
              >
                {'Learn more'}
              </Link>
            </DefaultFooterText>
          }
        />
``` 

This issue will live in the design section of the checklist. 
<img width="363" alt="Screen Shot 2022-04-20 at 11 18 46 AM" src="https://user-images.githubusercontent.com/10720454/164296749-da66286c-5ee4-47de-9fa7-65d21aa40ed4.png">

So the actual check will live here: `packages/story-editor/src/components/checklist/checks` 
and it will need to be imported and added here: `packages/wp-story-editor/src/components/checklist/design/index.js` 
This is because there are certain checks that are WordPress specific. 

A good example of another issue in the same style is here: `packages/story-editor/src/components/checklist/checks/storyAmpValidationErrors.js` 

Logic for this issue will live in the `checklist/checks/firstPageAnimation.js` (or whatever you end up calling it). You will need to check to see if the first page of a Story has animation. If it does then the check should render. 
You can find the relevant Story Page info through `useStory` - state holds `pages`. We want to know if pages[0] holds animations. There's enough examples of similar in the codebase to use the above to gain familiarity. 

Please include new unit tests for the check (follow the example of the other tests in that directory) and also include a new karma test (`packages/story-editor/src/components/checklist/karma`)

## Acceptance Criteria 
- New checklist design issue that renders when a first page of a Story has animation 
- Affiliated tests

**Comment by mwritter** [comment]
Hey @swissspidy - do we know what verbiage we want to use for this checklist item, and what the `link` should reference here?

**Comment by swissspidy** [comment]
Heya, thanks for raising that 👍 

I think we can use the same verbiage as for the other warning in the panel.
The link can point to `https://wp.stories.google/docs/how-to/animations/`. We'll make sure to add some content there for this.

Ideally with a `trackClick` event handler attached so that we can measure clicks on this link. e.g.

```const onClick = (evt) => trackClick(evt, 'click_checklist_cover_animations');```

----

Just a general UX question about this ticket here. Somehow this didn't occur to me before.

With #11416 disabling the animation panel on the first page and this ticket showing a warning for animations on the first page....

How can the user get rid of this warning?

Seems like we should add a "Remove animations" CTA button below the warning that automatically removes all animations from elements on the first page.

(`VideoOptimization` checklist check also has such a CTA button, so there's precedence)

cc @agingoldseco
