### ISSUE TITLE
Missing Campaign Parameters - Please help me understand

### ISSUE THREAD

**Issue by freestylemama** [swissspidy/web-stories-wp#11330]
I have been trying to figure out how to fix this issue with GA, and I'm hoping someone can help. 
On my site property (not WS property) I get the notification below. 

I added parameters to post links such as https:// dianarambles . com/cat-condo/?utm_source=discover&utm_medium=organic&utm_campaign=ws-cat (w/o spaces) but I continue to get this message. (I followed a tutorial that suggested these parameters) I am not sure if I am missing something or I just don't get what this means. TIA!

Missing Campaign Parameters
First detected: Mar 19, 2022 10:23:09 AM
Each Google Analytics hit can have parameters for source, medium and campaign that defines the context of each acquisition to your website. In order to properly track where your website's visitors come from, you should fill out all of these parameters wherever possible. If you're missing one or more of these parameters, then you're missing some insight into your visitors' behavior.
Property Diana Rambles is receiving hits with missing campaign parameters. Some examples (in the format "Source/Medium/Campaign") are:
web stories/(not set)/(not set)
To avoid receiving Google Analytics hits with missing parameters, ensure that links referring to your site have the URL parameters utm_source, utm_medium, utm_campaign all filled out.

**Comment by swissspidy** [comment]
Heya

Please note that we usually only provide support on the [WordPress.org support forums](https://wordpress.org/plugins/web-stories/support/), and that for questions about Google Analytics we generally refer to the [Google Analytics help site](https://support.google.com/analytics).

That said, since you are already here:

Your example with the parameters (`https://dianarambles.com/cat-condo/?utm_source=discover&utm_medium=organic&utm_campaign=ws-cat`) looks fine to me and seems in accordance with the [Google Analytics documentation](https://support.google.com/analytics/answer/1033863?hl=en).

However, on some of your stories, for example https://dianarambles.com/web-stories/easy-chicken-patty-parmesan-recipe/, you have only added the `?utm_source=web+stories` parameter but not `utm_medium` or `utm_campaign`. You need to all three parameters in order to resolve this warning.

Incorrect: `https://dianarambles.com/ad-chicken-patty-parmesan-recipe/?utm_source=web+stories`

Correct: `https://dianarambles.com/ad-chicken-patty-parmesan-recipe/?utm_source=web+stories&utm_medium=organic&utm_campaign=ws-cat`

As per the [Google Analytics documentation](https://support.google.com/analytics/answer/1033863?hl=en)

* When you add parameters to a URL, you should always use `utm_source`, `utm_medium`, and `utm_campaign`.
* `utm_term` and `utm_content` are optional.
* `utm_` is simply the required prefix for these parameters.

Hope that helps!

**Comment by freestylemama** [comment]
Thank you. Sorry for asking at the wrong place. I appreciate your help!
