### ISSUE TITLE
Floating toolbar is sometimes invisible to users, but still exists

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11377]
## Bug Description

We have experienced a number of occasions where the floating toolbar is not presented to user on element selection, but it's still on page, as some of the controls within can still be interacted with.

Here is video of me encountering this yesterday
https://user-images.githubusercontent.com/58738530/165594360-3c2e7f9d-f3ad-4d06-bd0e-bb6d4ce377b0.mp4

## Expected Behaviour

Floating toolbar should be presented whenever it's expected, should be visible, and should be usable.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by felipebochehin87** [comment]
Tested in Chrome, Safari and Firefox.

1. Added 3 elements to the canvas
2. Dragged 1 element out of the page and clicked on the remaining ones - FM displayed
3. Resized screen so that the FM was bigger than the canvas, the elements, etc., and clicked on the elements - FM displayed
4. Dragged and dropped text element, resized it many times, dragged again - hints were not displayed while element was being dragged - FM hidden and inactive as expected
5. FM displayed again when I dropped the text element and clicked on it
6. Tried zoom in/zoom out, multiple elements selected, resizing images, videos, adding products... - FM displayed

Video below:

https://images.zenhubusercontent.com/235435637/28eebed6-c587-4142-a19f-26df86b88a60/11627.mp4
