### ISSUE TITLE
Stories are not setting their publish date correctly.

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11403]
## Bug Description

In testing we've discovered that stories that have previously been saved as a draft, will retain this date and time as the published date, no matter when the story is actually published. This is inaccurate and is causing problems for clients who may be editing stories for extended period of time. 

## Expected Behaviour

The publish date time should reflect the actual date & time when the story was succesfully published, not when the story first began life as a draft.

example URL - https://stories-new-wordpress-amp.pantheonsite.io/web-stories/teststory4/ 

## Steps to Reproduce

1. Create a story
2. Wait a day
3. Publish the story
4. note that the publish date / time is the day previous

## Screenshots

1. Unpublished draft, view of the document publish time, which is incorrectly indicated a date in the past:
![Screen Shot 2022-04-29 at 3 08 47 PM](https://user-images.githubusercontent.com/58738530/166030992-888732da-05ed-46bd-a979-f685e3b83aa7.png)
2 Same story - prepublish modal also showing the publish date/time set to when the story was first saved as a draft 

![Screen Shot 2022-04-29 at 3 09 09 PM](https://user-images.githubusercontent.com/58738530/166034715-422990e6-471b-43cb-809a-56210e0f1702.png)

3. Post publish - Structured data check reveals the old date is retained
![Screen Shot 2022-04-29 at 3 09 55 PM](https://user-images.githubusercontent.com/58738530/166036824-5941949d-4f55-4d58-abdf-cd70f7dd119c.png)
4. Post publish - Published story in dashboard with old date displayed as the published date/time - 
![Screen Shot 2022-04-29 at 3 10 10 PM](https://user-images.githubusercontent.com/58738530/166038784-043c0b46-5f2c-4c01-b50a-2b9384433ee9.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Previously: #7692 / #7759

The "Immediately" option still exists when creating a fresh new story, but it's gone soon after.

It seems like the above ticket never fully resolved this issue.

At first glance it looks like this is related to how we store _all_ the story data in the `StoryProvider` context. So once a story is opened in the editor, the current date is stored in state. Then whenever you save the story, that same date is always sent to WordPress, even if you haven't manually changed the date in the date picker.

Simpler steps to reproduce (more or less):

1. Create new story, add some content, save it.
2. Refresh the page 1 minute later.
3. At this point we'll still have the _old date_ (from 1 min ago) in state
4. Make some change, save story.
5. Refresh the page
6. Open the publish modal, see the _old date_ in the date picker

Compare this to Gutenberg where only the _actually changed fields_ are sent to the WP REST API, not _all fields_. Which is why it does not suffer this same problem.

cc @barklund @merapi for thoughts on how we could best fix this.

**Comment by merapi** [comment]
> cc @barklund @merapi for thoughts on how we could best fix this.

We discussed it yesterday, it looks like P1/P2, not P0, so we are moving that to the next sprint.

**Comment by felipebochehin87** [comment]
Looks good in QA.
