### ISSUE TITLE
Enable option from the users upload yours stories like instagram, behance or facebook.

### ISSUE THREAD

**Issue by Felipemauah** [swissspidy/web-stories-wp#11409]
Hello! Thanks for the amazing job inthis plugin (WP Stories).

My request is about a new feature: Enable option from the users upload yours stories like instagram, behance or facebook.

In my business (content community+ marketplace), my goal is supply a tools to my cliente sell your product and publish your content.

This option is a very important, not only to me, but for the many and many users. I know that feature is not simple to develop, but if this feature made it into your roadmap it would be fantastic, as we would know that there would soon be a possibility for us to provide this feature to our customers.

Thank you so much again for the beautiful work.

**Comment by swissspidy** [comment]
Hi there

Glad to hear you like the plugin and thanks a lot for sharing your feature request!

We actually track this one already in #7747 and it's also mentioned on the [public roadmap](https://docs.google.com/spreadsheets/d/10DZZrWJdkjcJXD1vL0VG0PqRhsIqaHkacF_ujOdEwJc/view#gid=0) under "Share to social media"

As you say, it's not simple to develop, which is why we don't have any estimate right now on _if_ and _when_ we are going to build something like this. Just know that this is something on our radar.

Any progress in this area would be shared on #7747, so you could follow that one for any progress. But again, it's not a top priority right now.
