### ISSUE TITLE
Add "more" button option to Web Stories blocks

### ISSUE THREAD

**Issue by mxbclang** [swissspidy/web-stories-wp#11414]
## Feature Description

<a href="https://wordpress.org/support/topic/some-requests-ideas-and-errors/">A user in the forum requested</a> the addition of a "more" button on the Web Stories blocks so that users can easily access all of a site's stories without having to go to the archive page.

Here was their specific request: "Let’s say we can show up to 20 stories with the widget and we have more than 20 stories. Then there might be a little button that will open all the stories in the last line. Now I think maybe, maybe it would be better: 10 stories are shown, click the “more” button to load more and at that moment, 10 more stories will be added to the widget without opening the archive page. If there are other stories later, the button at the end of the list is clicked again. Yes, that would be great."

**Comment by halilesen** [comment]
![more](https://user-images.githubusercontent.com/73847687/167622970-b0df6e04-ae3e-4e0f-8d33-7fff755ecbaf.jpg)

Ok, I didn't get the picture very well, but it looks like 90% of what I want it to be. This will increase the loading speed of the page. Because not 20, but fewer stories will be loaded in the first place. If the stories are relevant users will want to see more.

Of course, one should not forget: If the user opens a story and then moves on to the next one, the uploaded stories should also be added to the list.

**Comment by ParasKatoch** [comment]
This is a much-needed feature. I was trying for the last few days to figure out the solution for the "view more stories" button. Guess this feature isn't available yet. The max I can set is 20. Will follow the thread for updates. Please let me know if anyone of you got some code to get this working. Thank you!

**Comment by bishwasbh** [comment]
Also, this "view more option" isn't working.
![image](https://user-images.githubusercontent.com/75174691/193982081-e7a05709-2da6-4c9f-976a-e547cb75c2ae.png)

**Comment by Bishwas-py** [comment]
Also, this "view more" option isn't working.
![image](https://user-images.githubusercontent.com/75174691/193982081-e7a05709-2da6-4c9f-976a-e547cb75c2ae.png)

Whenever I click on "View More Stories" it re-renders the same and happens nothing.

**Comment by swissspidy** [comment]
The "View All Stories" link points to the Web Stories archive page. If you use the Web Stories block on that page itself, yes, it will just point to the current page.

We don't have a good solution for that yet, which is why tickets like the one here are still open.

In the meantime, a possible workaround is to use the Query Loop block in WordPress to display your latest stories on your archive page together with their poster image and proper pagination.

If there's any update on this matter, we'll share them here.
