### ISSUE TITLE
Bug With Latest Version Of Web Stories

### ISSUE THREAD

**Issue by DanielCryptoK** [swissspidy/web-stories-wp#11472]
As you may already know as I have been hitting every forum trying to solve the problem that you said was not related to web stories but after two weeks and a few hundred pounds lighter in developer costs, he tells me it is a bug in web stories that is stopping any tests such as amp tetst, url inspection test, rich results.

On version 1.9.0 which I have had to just go back to all those test work

When I update to 1.20.0. non of those test work.

My website statistics for two websites have been destroyed due to this error so hoping someone can help as I need that version for the ability to add audio to each page.

**Comment by swissspidy** [comment]
Heya

I understand the frustration that this must have caused you, but there's no signal on our side that would indicate a bug with the Web Stories plugin itself. We do not get a similar issue with any other live story created with the plugin.

Usually when the AMP Test tool can't access a webpage it's because the server (firewall, CloudFlare, etc.) blocks access.

In such a case, please use the help options provided in the AMP Test tool and check your server configuration. 

In a quick test, the AMP Test tool can access https://bitcoin-casino-no-deposit-bonus.com/web-stories/tester/ just fine.

<img width="1728" alt="Screenshot 2022-05-11 at 08 16 44" src="https://user-images.githubusercontent.com/841956/167781429-e056c193-ffc1-4b87-a634-82743f9eae95.png">

It can also access https://bitcoin-casino-no-deposit-bonus.com/web-stories/sportsbet-review/ just fine, but that story has some AMP validation errors.

<img width="1728" alt="Screenshot 2022-05-11 at 08 16 18" src="https://user-images.githubusercontent.com/841956/167781381-63c46a92-f1b3-46f9-8532-09a97a166dd4.png">

They're related to videos which have missing URLs. No idea how that would happen. Try removing videos and adding them again.

Other stories like https://bitcoin-casino-no-deposit-bonus.com/web-stories/decentral-games-review/ are accessible and valid AMP.

<img width="1728" alt="Screenshot 2022-05-11 at 08 18 53" src="https://user-images.githubusercontent.com/841956/167781723-390b1746-d1e0-40cb-95ac-c55b1b166356.png">

I don't see any bug here.

If you continue running into scenarios with the AMP Test tool not being able to access your webpage, please use the help options provided in the tool.

**Comment by DanielCryptoK** [comment]
Hi,

You dont see any errors as I have changed it to the previous version. When I change to the updated version that is when it does not work. The latest update you did effects both my websites, the second one it only effects it when cloudflare is turned on with the latest version, however the one we are talking about works with cloudflare turned on for the previous version, therefore I believe you added something to the latest version that conflicts with something. What could it be that you added to the latest version that is doing this?

**Comment by swissspidy** [comment]
I wouldn‘t know what change could have caused this difference, but I also don‘t know the details of your CloudFlare setup.

Can you confirm things work fine with CloudFlare turned OFF? If so, I recommend reaching out to their support.

**Comment by DanielCryptoK** [comment]
I am just in the process of directing my domain to go directly through cloudflare rather than via the server and then to cloudflare in my DNS settings, could this have an impact on anything?

**Comment by DanielCryptoK** [comment]
Both sites on your previous version work no problems what so ever

**Comment by swissspidy** [comment]
It‘s possible that this has an impact, yes. If the AMP Test Tool has issues accessing your site it usually means there is some kind of server configuration issue that blocks Google infrastructure from accessing your site. Can be DNS, CloudFlare, firewalls, internal server errors, etc.

We don‘t maintain the AMP Test Tool, so I can‘t provide specifics about its inner workings or what exactly is the issue in this specific scenario. So that‘s all we can really help here I‘m afraid.

**Comment by DanielCryptoK** [comment]
I have the ip addresses of google bot that does the test for amp along with allow any known bots in cloudflare. Please also see other settings and advise as I have been talking to cloudflare support for 2 weeks getting no where. 

https://www.webpagescreenshot.info/#v2=1BK2UwLiC

https://www.webpagescreenshot.info/#v2=_E7WemK4E

**Comment by DanielCryptoK** [comment]
Below is the last email I got from my hosting company who spent two weeks trying to figure it out

Hi Daniel,

This is the result I'm getting when doing test against URL: http://nonfungibleownership.com/web-stories/theta-review/
https://i.imgur.com/KWKvOqI.png
 
When I tried checking the logs, cross-matched with visits using cache-busting, so that we get fresh Apache response, it shows here visits generated by the test tool
https://i.imgur.com/bXhcfyz.png
I'm not too sure if these non-static IPs will be useful to you and we're not clear if it really has to do with blocks, although hinted in online threads about this issue.
Problems like yours require isolation and since issue emanates from use of Cloudflare, please look for a developer that has made it work using Cloudflare in the DNS layer, for past projects.
FYI, it may be worth checking with Cloudflare if they have suggestions, hopefully, you get someone familiar with web stories. 
It seems this is out-of-scope though as DNS support, same as our end, hosting, is not really able to handle queries about why a 3rd-party validator fails when Cloudflare is enabled.
It may require changes from Cloudflare end but ideally, instructions on what those should be should come from a developer familiar with this tech (web stories and validator) you rely on.
 
Hope you figure this out.

**Comment by DanielCryptoK** [comment]
The developer I am paying to fix this wants to know: how come firewall blocked bot for latest version but not for downgraded version

**Comment by swissspidy** [comment]
We don‘t know how your CloudFlare firewall works so we can‘t really tell you why it seems to work for one plugin version but not the other.

I‘m happy to keep an eye on this matter and let you know if we find something, but right now in our position on this plugin we can‘t really help you with issues with the AMP Test Tool and CloudFlare.

**Comment by DanielCryptoK** [comment]
Please understand my situation Pascal, I have been trying ever since your last update to fix this and I am about to have a breakdown because of the stress of it. With what is going on with covid, world war 3 and everything crashing it is a very stressful time. I have spoken with cloudflare for 2 weeks without getting resolved, I have had my hosting look at it for over a week and can not resolve, I have hired a developer and can not solve and my business and income is getting destroy because of it. I dont understand why you can not help when it is directly linked to the last update as everything works completely fine even with cloudflare turned on with the previous person. Please, please can you see if you can find someone at cloudflare to help as I am shocked that I am the only person to suffer from this as cloudflare is used by millions of users and this effects both my websites which have completely different set ups, I must be the most unlucky guy in the world to have two completely different set up websites that dont work in the URL test and everyone elses is working ok.

**Comment by DanielCryptoK** [comment]
Is there a contact email for someone at the AMP test tool you can provide me? It is not just the amp tool, it is the url inspection tool, rich snippets tool etc.

**Comment by swissspidy** [comment]
We do not provide support via email. FWIW, we also don‘t provide support via GitHub, so please keep this in mind. We simply don‘t have the bandwidth to help with site-specific edge cases like this.

If you update to the latest version again I can try to take another look next week, but that‘s the last offer. If that does not bear any fruits we‘ll have to close this issue.

**Comment by DanielCryptoK** [comment]
Its ok, the guy working on my hosting has finished transferring the domain from the hosting company Cloudways to Cloudflare via DNS settings and finally that has fixed it. That problem has honestly taken me to the point of a nervous breakdown to fix it, no idea why your last update causes this to happen.
