### ISSUE TITLE
Dashboard: Add publish date filter

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11586]
## Feature Description

Users have requested that the Dashboard be updated to provide the ability to select and sort on Date Published in this view.

Specific UI request was that the word Draft would appear for unpublished stories and could be easily filtered on.

## Additional Context

This supports users who have multiple stories in draft for an extended period as they are authored

**Comment by swissspidy** [comment]
Is filtering by date already possible on the „All Stories“ page? If so, I‘d recommend using that for now.

**Comment by mwritter** [comment]
@bmattb @swissspidy - I have a couple of question before I start on this one
> ...select and sort on Date Published in this view.
For 'sort on Date Published' Im assuming we can just add an entry to the existing 'sort' dropdown for 'Date Published'?
For 'select on Date Published' 🤔 should we a dropdown filter with specific published dates, or maybe a date picker?

> Specific UI request was that the word Draft would appear for unpublished stories and could be easily filtered on.
Could you elaborate on this? You can filter by 'Drafts' on the Dashboard and apply sort and filters (author and taxonomy) to the 'Drafts' - So is the main ask here just to add a new entry to the 'sort' dropdown for 'Date Published'?

**Comment by swissspidy** [comment]
Sorting by publish date is already possible by selecting the "Date Created" option from the sort dropdown.

IIUC the request was for _filtering_ by specific dates, e.g. all stories published in May 2022. Like you can already do on the "All Stories" page. Example:

<img width="872" alt="Screenshot 2022-06-21 at 17 30 21" src="https://user-images.githubusercontent.com/841956/174838926-eb7000dc-12b5-4790-bc95-67a0198381ee.png">

(Note that this filter dropdown works for both _published_ and _scheduled_ stories. It only shows months that actually have)

Though FWIW I am not sure whether we actually want to add such a filter because this can be achieved via the "All Stories" page already and I don't think we necessarily want to replicate everything from that page.

Perhaps @aaskedall and @gajasinski can chime in here to help prioritize this

> > Specific UI request was that the word Draft would appear for unpublished stories and could be easily filtered on.
> 
> Could you elaborate on this?

+1 I'd also like to understand this better.

**Comment by bmattb** [comment]
I am going to close this for the following reasons:

1. Users can filter the dashboard view to present only Draft (unpublished) stories by using the Draft pill at top of the dashboard
2. While the request was for the ability to sort on published date in the Dashboard, this is possible already today in the All Stories page by selecting Published stories and sorting on the date.
