### ISSUE TITLE
Dashboard: Adjust Filter Dropdown Width

### ISSUE THREAD

**Issue by sblinde** [swissspidy/web-stories-wp#11665]
## Feature Description

As a part of our Filters improvement and enhancement work, we should have the filters that are on the grid view of the Dashboard also be visible in the List view.

## Acceptance Criteria

- As a part of ensuring the list view is functional, let's be sure that the width of the dropdown elements in both the List and Grid view are appropriately sized.
- Dropdowns should also scale within the space in the top of the dashboard appropriately. See: https://github.com/GoogleForCreators/web-stories-wp/pull/11625#issuecomment-1153728314

## Out of Scope

- ~All filters that exist within the Dashboard Grid View should also exist as filters for the list view of the Dashboard~ Moved to https://github.com/GoogleForCreators/web-stories-wp/issues/11767
- ~This should be built in a way that adding filters in the future should work in both the List and Grid views of the Dashboard.~ Moved to https://github.com/GoogleForCreators/web-stories-wp/issues/11767

## Additional Context

This feedback was requested as a part of https://github.com/GoogleForCreators/web-stories-wp/pull/11625#discussion_r892222772

It may be easier to accomplish this after the core work is done with #11620

**Comment by sblinde** [comment]
We may need to check in with UX for the following feedback:

- Dropdowns should also scale within the space in the top of the dashboard appropriately. See: https://github.com/GoogleForCreators/web-stories-wp/pull/11625#issuecomment-1153728314

**Comment by mwritter** [comment]
@sblinde @swissspidy @aaskedall - I have a couple of design questions Ill add them here so that we can discuss them.
1.) This ticket is primarily to adjust the dropdown widths so that the dropdown 'labels' do not get truncated. My question here is; should there be so sort of 'max' length for these elements? The 'select', 'options' and 'placeholder' or should we allow them to be as long as specified?
Super long Placeholder:
![No Max Length Placeholder](https://user-images.githubusercontent.com/14057928/174661894-8ae2bcbd-0aa1-41f8-aced-e97ed49959e2.png)

Super long Options and Select:
![No Max Length Option and Select](https://user-images.githubusercontent.com/14057928/174661905-ded58fa8-be0f-4efb-9835-0b50bb42980f.png)


2.) Ultrawide support / suggestion
Currently we pull all the filters and the grid type toggle to right.  For ultrawides or large screens this is hard to navigate.
![Far Right](https://user-images.githubusercontent.com/14057928/174658773-b4ff515d-f445-4028-85b5-06f8a4fb3649.png)
Would it make more sense to keep the filters and the 'grid type' toggle all on the left like:
![Keep Left](https://user-images.githubusercontent.com/14057928/174659324-67ab4220-a868-43a5-9f38-5bf0a9443357.png)

**Comment by mwritter** [comment]
@sblinde @swissspidy @aaskedall - Suggested look and feel, with arbitrary max length.

https://user-images.githubusercontent.com/14057928/174669949-9e1e3a75-dbf0-400c-8b64-4938d89990aa.mp4

**Comment by felipebochehin87** [comment]
Changes look good to me. Tested in Safari, Firefox and Chrome.
