### ISSUE TITLE
Unable to save your story - Error 400 'rest_missing_callback_param' in console

### ISSUE THREAD

**Issue by pirmax** [swissspidy/web-stories-wp#11774]
## Bug Description

I use the 1.22.0 version of plugin, and when I want to create a story, I get this popup...

<img width="558" alt="CleanShot 2022-06-22 at 08 45 01@2x" src="https://user-images.githubusercontent.com/1739235/174961810-c58414ae-39b4-49d8-bf5d-2a41c2692c9a.png">

The error is Chrome console is `GET https://www.domain.com/wp-json/web-stories/v1/status-check?_locale=user 400`
The error in network on Chrome is `{"code":"rest_missing_callback_param","message":"Param\u00e8tre(s) manquant(s)\u00a0: content","data":{"status":400,"params":["content"]}}`

## Expected Behaviour

At least have access to the interface and have it fully working.

## Steps to Reproduce

Install the 1.22.0 version of plugin on fresh installation of WordPress 6, without plugin.

## Additional Context

- Plugin Version:  1.22.0
- WordPress Version: 6.0
- Operating System: MacOS
- Browser: Google Chrome / Safari

**Comment by swissspidy** [comment]
HI there

Thanks for your detailed report!

Unfortunately I cannot really reproduce this on a fresh install.

Does this also happen in another browser and when in incognito mode?

What stands out from your report is this:

`GET https://www.domain.com/wp-json/web-stories/v1/status-check?_locale=user`

It should be `POST`, not `GET`.

Could you please follow these steps to see what's going on under the hood?

1. Open browser dev tools (press <kbd>F12</kbd>)
2. Open the Network tab
3. Filter by Fetch/XHR
4. Reload the editor
5. Search for the entry containing `http://web-stories/v1/status-check?_locale=user`
6. Share details about the entry here

Example:

![Screenshot 2022-06-22 at 09 49 28](https://user-images.githubusercontent.com/841956/174974005-105a4ee4-c99d-4bab-9c29-9565767201d0.png)

(again, see how it says `POST`, not `GET`)

Another question:

Did you perhaps have any service workers installed? These are added for example when installing the PWA WordPress plugin.

To check, open dev tools again, go to the Network tab and click on Service Workers. If there is an entry:

1. Deactivate all other plugins
2. Click on "Unregister". Then perform the steps above again.

If that also doesn't help, it might be best for you to share your Site Health information with us so that we can spot any anomalies.
