### ISSUE TITLE
Page Attachment: Link icon not displayed on canvas

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#11847]
## Bug Description
The link icon is not displaying on the canvas besides the Call to Action (page attachment). Note that it renders when previewing the [story](https://testsite.cmsdevrel.com/web-stories/1442/). 

## Expected Behaviour

The link icon should pull through and display on the page attachment. 

## Steps to Reproduce

1. Add Call to Action to page (https://www.wikipedia.org)
2. See link icon load
3. Note the image logo does not pull through beside the Learn More text.

## Screenshots

<img width="1198" alt="Screen Shot 2022-06-30 at 11 05 31 AM" src="https://user-images.githubusercontent.com/66372350/176713372-5f2b0868-88fb-4360-9128-5a833f48a0d2.png">

<img width="1178" alt="Screen Shot 2022-06-30 at 11 05 20 AM" src="https://user-images.githubusercontent.com/66372350/176713298-15754c56-660f-4a1d-80a1-99dbc695bad9.png">

## Additional Context

Related Support topic: https://wordpress.org/support/topic/link-fetching-icon-not-working/

- Plugin Version: 1.22.0
- WordPress Version:
- Operating System: macOS
- Browser: Chrome

**Comment by swissspidy** [comment]
Looks like the icon isn't displayed there because of CORS, since we use the link icon as CSS background image:

https://github.com/GoogleForCreators/web-stories-wp/blob/512328ada20ed77687817ee479bd09255836ca61/packages/story-editor/src/components/canvas/pageAttachment/index.js#L113-L122

Switching to use a proper `<img>` with `crossOrigin=anonymous` works:

![Screenshot 2022-06-30 at 17 34 50](https://user-images.githubusercontent.com/841956/176718213-f3dca31e-5d3f-46bc-9e7c-be9b8b5edc5c.png)

Should be an easy fix.

**Comment by spacedmonkey** [comment]
Funny enough, I fixed this issue in https://github.com/GoogleForCreators/web-stories-wp/pull/11792
