### ISSUE TITLE
Failed to save the story: The response is not a valid JSON response.

### ISSUE THREAD

**Issue by StefanSTV** [swissspidy/web-stories-wp#11860]
Hi there.

I am trying to create webstories for a client and it seems that every-time i add a new slide and try adding text or images, i get the error on autosave or when saving manually: Failed to save the story: The response is not a valid JSON response.

I bugs me a lot and i have no way of figuring out. Please help

Thanks

**Comment by swissspidy** [comment]
Hi there

Sorry to hear that you're having issues with saving stories.

Typically this error message occurs when there is some plugin/theme conflict or some server configuration issue causing some PHP errors and thus making the response invalid JSON.

In order to help you resolve this issue we'd need a bit more information though. Since we do not provide support here on GitHub, please [create a new topic in the official support forums](https://wordpress.org/support/plugin/web-stories/) with some more details, such as your Site Health information.

Also try some typical debugging steps like temporarily disabling all other plugins to see if the issue still occurs. You can also reach out to your hosting provider to check the error logs for your site to see if anything stands out.

Second, to see what is causing the invalid response, you can open your browser's dev tools (press F12) and then analyze the failed request in the Network tab, under "Response". Like so:

![Screenshot 2022-07-04 at 11 33 20](https://user-images.githubusercontent.com/841956/177127041-6f2e91d5-0438-4fcd-a1dd-9b25a7d017ff.png)

Since we only offer support in the forums, I will therefore close this ticket so we can continue the discussion there.
