### ISSUE TITLE
3P Media: Enable stickers support by default

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#11936]
## Feature Description

Initially added in #11880. Now we wanna enable it by default in the next release.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #12019.

1. Started a new story using an old branch - stickers are enabled when experiment is ON, disabled otherwise
2. Changed to PR app 12019
3. Checked experiments - stickers experiment is enabled by default and cannot be disabled
4. Started a new story and checked stickers - they're displayed and ready for use

Chrome, Safari, Firefox
Author, Admin, Editor, Contributor

https://images.zenhubusercontent.com/235435637/c1accd57-e600-44fc-bfd4-91bbcf6beb39/2022_07_26_15_29_34.mp4
