### ISSUE TITLE
Page-Level Page Advancement Setting

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12210]
## Feature Description

Currently we only support changing the page advancement (manual/automatic, duration) for the whole story for consistency reasons.

We now wanna try to allow this on a per-page basis as well.

**Comment by miina** [comment]
Q: I assume that the per-page setting will override the global setting for the Story. Should there be a way for the user to reset all to global or is it ok to just let the user go through the Pages one by one if needed?

Also, we currently have Auto and Manual for the global setting, however, should there also be a `null` option per-page so that the page would follow the global setting? In this case perhaps the Switch option doesn't work.

Or perhaps we could have a checkbox saying "Override the global Page Advancement" (or something similar) which would then display the Switch for choosing between Auto / Manual.

Thoughts? cc @merapi @swissspidy

**Comment by merapi** [comment]
> Should there be a way for the user to reset all to global or is it ok to just let the user go through the Pages one by one if needed?

I think we can start without that extra option, we can add it later if needed (after UX feedback?).

> Also, we currently have Auto and Manual for the global setting, however, should there also be a null option per-page so that the page would follow the global setting? In this case perhaps the Switch option doesn't work.

I was thinking about three state switch (new or modified component) or checkbox to override it (like you):

![image](https://user-images.githubusercontent.com/21036224/189329531-9092e68c-1f35-4c64-b924-275dc0c77e8a.png)

(Options not visible or with scrim)
![image](https://user-images.githubusercontent.com/21036224/189330579-f4e37843-645b-45a1-bcf5-2a05fe9ff2c5.png)

![image](https://user-images.githubusercontent.com/21036224/189330624-73ec6b01-b411-4581-bdaf-0f73a7e75807.png)

**Comment by bmattb** [comment]
@aaskedall will provide updated designs here
