### ISSUE TITLE
Floating toolbar menu item uses non-standard tooltip

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#12252]
## Bug Description

the More button on the floating toolbar has a non-standard tooltip presentation that is different than all others:

![image10](https://user-images.githubusercontent.com/58738530/188949150-e30e780b-c103-475b-bc7e-915a8005bc80.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
This appears to be because many of our buttons have `title` attributes. I don't know why, as it doesn't make sense for text buttons. `aria-label` & custom tooltips should (where applicable) be enough.

In this case here, I'd say we don't need a custom tooltip that just says "More" as that is pretty useless.

We can remove the `title` attribute here:

https://github.com/GoogleForCreators/web-stories-wp/blob/3f9e33237b3f7f15e7333a4427a24f2455a82308/packages/story-editor/src/components/floatingMenu/elements/shared/text.js#L32-L38

And also here:

https://github.com/GoogleForCreators/web-stories-wp/blob/3f9e33237b3f7f15e7333a4427a24f2455a82308/packages/story-editor/src/components/panels/design/sizePosition/sizePosition.js#L364

https://github.com/GoogleForCreators/web-stories-wp/blob/3f9e33237b3f7f15e7333a4427a24f2455a82308/packages/story-editor/src/components/library/panes/media/common/attribution.js#L53

A good opportunity to go through the code base and find other useless instances.
