### ISSUE TITLE
AMP Robot TXT Blocking Google Bot

### ISSUE THREAD

**Issue by DanielCryptoK** [swissspidy/web-stories-wp#12628]
For the web stories it does not use my robot txt but the amp version which I dont think it is possible for me to change on wordpress???  

https://bitcoin--casino--no--deposit--bonus-com.cdn.ampproject.org/robots.txt

Disallow: /i/ is what's blocking google bot from been able to crawl my images.

How do I remove the Disallow: /i/ from the ampproject.org/robot.txt ???

**Comment by swissspidy** [comment]
Hi there, I‘ve answered this already at https://github.com/GoogleForCreators/web-stories-wp/issues/12384#issuecomment-1303298114 and I will copy my reply here for visibility.

**tl;dr:** there is no problem here.

We do not provide support for crawling and indexing questions here, please check out https://developers.google.com/search/docs/crawling-indexing and the help community there for these kind of questions.

That said, this looks as expected.

`https://bitcoin--casino--no--deposit--bonus-com.cdn.ampproject.org/i/s/bitcoin-casino-no-deposit-bonus.com/wp-content/uploads/2021/07/bcnbd-rounded-512-250x250.png` is cached version of your image `https://bitcoin-casino-no-deposit-bonus.com/wp-content/uploads/2021/07/bcnbd-rounded-512-250x250.png` in the AMP cache.

The AMP cache blocks indexing from crawlers, because obviously a crawler should index the original at `https://bitcoin-casino-no-deposit-bonus.com/wp-content/uploads/2021/07/bcnbd-rounded-512-250x250.png` and not the cached version.

So I don't see an issue here. But again, please use https://developers.google.com/search/help for any questions related to search rankings.

**Comment by DanielCryptoK** [comment]
I did add it to google communities who gave me the answer that it was the robot txt blocking google bot and I should report it.

https://support.google.com/webmasters/thread/187040932/web-stories-images-blocked-robot-txt

So the screen shot of the test results is suppose to be blank https://www.webpagescreenshot.info/#v2=DhsW38b1Z

And the images are suppose to show that they are been blocked by robot txt https://www.webpagescreenshot.info/#v2=iPReLMIN8

Can you please confirm that both images are correct.

**Comment by DanielCryptoK** [comment]
@swissspidy Are you able to confirm or deny that the /i/ in the web stories images url links that is been blocked by the amp robots txt is having zero effects on google bots ability to crawl the web stories. It only needs to be a yes or no answer so please help.

**Comment by swissspidy** [comment]
I repeat: I see no problem here.

Again, if you have questions about indexing, crawling, etc. please refer to https://developers.google.com/search/docs/crawling-indexing and the help community there.

We do not provide support here.

**Comment by DanielCryptoK** [comment]
@swissspidy I have just updated your plugin and now get the below error, please advise how to fix

amp-story.js:474 
        
       Uncaught TypeError: Cannot read properties of null (reading 'setState')
    at jn.Gb (amp-story.js:474:24)
    at jn.Io (amp-story.js:1771:52)
    at amp-story.js:792:53
    at Es.fire (observable.js:63:7)
    at zs.ai (ampdoc-impl.js:655:37)
    at zs.overrideVisibilityState (ampdoc-impl.js:562:12)
    at Object.tl (viewer-impl.js:535:17)
    at Object.receiveMessage (viewer-impl.js:695:12)
    at amp-viewer-integration.js:198:21
    at wt.q (messaging.js:416:21)

**Comment by swissspidy** [comment]
Please report this at https://github.com/ampproject/amphtml
