### ISSUE TITLE
TypeScript: Convert canvas provider

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12661]

**Comment by miina** [comment]
Didn't notice it at first but looks like this is actually blocked by the media provider, couldn't find an issue for converting that one (@swissspidy LMK if you created one and I just can't find it for some reason).
I suppose it makes sense to stall this PR and continue once we have the media provider converted as well.

**Comment by swissspidy** [comment]
Which parts of the media provider specifically? Would be great if we can do this without having to convert the whole media folder but just the utils used by canvas provider

**Comment by miina** [comment]
It uses `useUploadWithPreview` which uses `useLocalMedia` which is included via `index.js` file that includes all the media provider related files basically. We could in theory import `useLocalMedia` directly instead of via the index file, however, that still requires converting the whole local media part at least + looks like also the general media provider related files. Thoughts?

**Comment by miina** [comment]
> It uses `useUploadWithPreview` which uses `useLocalMedia` which is included via `index.js` file that includes all the media provider related files basically. We could in theory import `useLocalMedia` directly instead of via the index file, however, that still requires converting the whole local media part at least + looks like also the general media provider related files. Thoughts?

Perhaps I can add a file declaration for it for now as a workaround... Will check. Otherwise I'll create an issue for converting the local media part of it (if it's possible).

**Comment by miina** [comment]
Added a declaration file for `useLocalMedia`, so now it should just be blocked by #12665 and otherwise be ready.
