### ISSUE TITLE
Add Forms to Web Stories

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#12788]
## Feature Description

A user requested a way for forms to be implemented in Web Stories. The form would be used to gather information like email and phone numbers should someone decide to enter it into the form. 

This request is similar to the [quizzes/polls](https://github.com/GoogleForCreators/web-stories-wp/issues/8725) feature request. 

## Additional Context

https://wordpress.org/support/topic/how-can-add-a-form-in-webstories/

**Comment by swissspidy** [comment]
Surprised that we never had an existing issue for this.

Back when forms support was introduced in the format, we checked how feasible it would be to add support to our editor. Turns out that it isn't very easy, especially when considering that people would ideally like to use their existing newsletter/forms plugins with stories etc.

Ultimately we decided that we won't consider adding forms support for the time being.

However, if there's enough interest/demand in it in the future, we can definitely reconsider.

For now, closing as "maybe later".
