### ISSUE TITLE
Test failures due to `KeyframeEffect`

### ISSUE THREAD

**Issue by miina** [swissspidy/web-stories-wp#12895]
## Bug Description
When enabling .tsx files, there are test failures with the following error in the `animations` package:
`ReferenceError: KeyframeEffect is not defined`

See https://github.com/GoogleForCreators/web-stories-wp/actions/runs/3824643543/jobs/6506964376#step:9:286

Also see https://github.com/GoogleForCreators/web-stories-wp/pull/12727/files#r1060169715 for context

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
That has less to do with tsx files but with this not existing in jsdom and some test using it.

We can mock it in setup-globals.js

**Comment by swissspidy** [comment]
Something like 

```js
window.KeyframeEffect = class KeyframeEffect {}
```

in `setup-globals.js` might already work.

**Comment by swissspidy** [comment]
Looks like this might be a bigger change.

There's all sorts of failures. Using `jsdom-testing-mocks` helps, but then there are still some failing tests in `packages/animation/src/components/test/provider.tsx`.

@barklund Since you rewrote the animation package, could you look into this?

To make sure `.tsx` files are tested, change this in `jest.config.js`:

```diff
-  testMatch: ['**/test/**/*.[jt]s'],
+  testMatch: ['**/test/**/*.{js,jsx,ts,tsx}'],
```

After that, `npm run test:js:watch packages/animation` will show the failing tests

**Comment by swissspidy** [comment]
Interestingly, this also includes failed tests because of `Error: Should not happen`. See #12946
