### ISSUE TITLE
Group layers alignment issue

### ISSUE THREAD

**Issue by jortega-consultant** [swissspidy/web-stories-wp#13154]
## Feature Description

Whenever a user selects 2 or more groups and proceeds to align them, the groups act as individual elements and align each one separately. Grouped layers should act as 1 unit when using the align and distribute commands.

## Alternatives Considered

Right now the editors who want to align multiple elements have to do it manually each element at a time.

## Additional Context

The groups should align/distribute as a group of groups, and not as individual elements.

When we align the following two groups:
![Screen Shot 2023-03-21 at 19 10 51](https://user-images.githubusercontent.com/111754166/226776417-480e7c26-514a-4e0f-aa83-6b365a877188.png)

The actual behavior is as follows:
![Screen Shot 2023-03-21 at 19 11 34](https://user-images.githubusercontent.com/111754166/226776518-67fb53a2-8050-45ba-8afb-da5f63d47fed.png)

The expected behavior is this:
![Screen Shot 2023-03-21 at 19 11 59](https://user-images.githubusercontent.com/111754166/226776542-6053bffc-3ffd-4aca-8c6c-018aba59f6df.png)

**Comment by ayushnirwal** [comment]
Groups currently align with respect to the bounding box created by selecting multiple groups.
This behavior is similar to what Figma and Canva does, and is a useful feature. 
Desired effect can be simply achieved by 
- making a group out of the groups, aligning that and ungrouping later. The problem with that workaround it that grouping 2 groups makes a group with all the element ( Set Union ) rather than  a group of group. Therefore ungrouping that leads to all elements in the groups as individual elements.
- Aligning one of the groups to the desired place which makes either a edge or a corner of the bounding box( selecting all the groups need to align ) aligned and then the collective alignment can be used.

**Comment by swissspidy** [comment]
Thanks for looking into it! Consistent behavior with other similar creation tools is a good sign, I wouldn't wanna change that.

The suggested workarounds sound reasonable to me. Note that supporting proper groups of groups is not planned, so the first one has a bit of a caveat when ungrouping.

Closing this as not planned for now.
