### ISSUE TITLE
Web Story Plugin Performance Issues with FCP, LCP, Scrolling, and Google Font- WordPress

### ISSUE THREAD

**Issue by maxags** [swissspidy/web-stories-wp#13191]
Hi everyone,

I wanted to start a discussion about the Web Story Plugin in WordPress and the issues it might be causing with performance metrics such as First Contentful Paint (FCP), Largest Contentful Paint (LCP), and the use of passive listeners for scrolling performance. I’ve noticed several issues with the plugin, including those related to FCP and LCP, as well as the use of passive listeners, and I’m wondering if anyone else has experienced the same thing.

For those who aren’t familiar with FCP and LCP, they are two of the metrics that Google uses to measure the user experience on websites. FCP measures the time it takes for the first piece of content to appear on the screen, while LCP measures the time it takes for the largest piece of content to appear. Both are important factors in user experience, and can have a significant impact on search engine rankings.

Unfortunately, since I started using the Web Story Plugin, my website’s FCP and LCP scores have dropped significantly. Additionally, I’ve noticed that the plugin does not use passive listeners to improve scrolling performance, which can also impact the user experience.

I’ve also noticed issues related to the use of Google Fonts, specifically with the URL https://fonts.googleapis.com/css2?display=swap&family=Poppins%3Awght%40400%3B700, which seems to be causing FCP issues on my website.

If anyone else has experienced similar issues with the Web Story Plugin, I’d love to hear about your experiences and any solutions you’ve found. Is there a way to optimize the plugin for better FCP, LCP, and scrolling performance? Are there any alternative plugins or tools that can help improve these metrics?

Let’s share our insights and solutions for improving performance with the Web Story Plugin, including passive listener issues and font-related issues like the one I’ve experienced.

**Comment by swissspidy** [comment]
Hi there, since you've already opened [a support topic](https://wordpress.org/support/topic/web-story-plugin-performance-issues-with-fcp-lcp-scrolling-and-google-font/) for the exact same thing, I am inclined to close this issue here as a duplicate. We can continue discussing in the support forums.

The two main things I'd like to repeat [from my response](https://wordpress.org/support/topic/web-story-plugin-performance-issues-with-fcp-lcp-scrolling-and-google-font/#post-16633239) are:

* The output of an individual Web Story on the frontend is powered by the Web Stories format, which falls under the AMP project's umbrella. All suggestions regarding things like passive event listeners should be reported over at https://github.com/ampproject/amphtml/
* You can use self-hosted fonts if you don't want to use the provided Google Fonts

**Comment by maxags** [comment]
mobile device-
https://prnt.sc/lGylTiINVh8w
https://prnt.sc/WWlZLaxV847Q
