### ISSUE TITLE
Calendar: Add Reset button for scheduled stories

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#13428]
## Feature Description
Add a reset button inside the calendar widget for stories that has already been scheduled for publishing.

Currently, there is no reset button in the editor's calendar widget for stories with scheduled publishing date.

Actual:
<img width="416" alt="Screenshot 2023-07-19 at 9 36 14 AM" src="https://github.com/GoogleForCreators/web-stories-wp/assets/66372350/0d904bf6-ac32-4113-b806-fe456e81d9fc">

Expected:
<img width="423" alt="Screenshot 2023-07-19 at 9 37 20 AM" src="https://github.com/GoogleForCreators/web-stories-wp/assets/66372350/ea5dfac2-e7d4-4d96-9920-16f280b0bf44">

**Comment by swissspidy** [comment]
@AnuragVasanwala assigning to you because it's in the milestone and should be a quick win for the next release. Please let me know if you have any questions.

Resetting the date basically means the scheduled date will be removed and the "Update" button gets turned into "Publish" to publish immediately. The same is possible in Gutenberg (the button is called "Now" there):

<img width="345" alt="Screenshot 2023-10-02 at 09 47 51" src="https://github.com/GoogleForCreators/web-stories-wp/assets/841956/a291af6c-5dc0-41b9-ab96-28917132b56b">

**Comment by AnuragVasanwala** [comment]
> @AnuragVasanwala assigning to you because it's in the milestone and should be a quick win for the next release. Please let me know if you have any questions.
> 
> Resetting the date basically means the scheduled date will be removed and the "Update" button gets turned into "Publish" to publish immediately. The same is possible in Gutenberg (the button is called "Now" there):
> 
> <img alt="Screenshot 2023-10-02 at 09 47 51" width="345" src="https://user-images.githubusercontent.com/841956/271911579-a291af6c-5dc0-41b9-ab96-28917132b56b.png">

@swissspidy Absolutely! I will integrate this feature ASAP and let you know if there is any doubt.
