### ISSUE TITLE
Web-stories ScratchCards

### ISSUE THREAD

**Issue by 7danny7** [swissspidy/web-stories-wp#13457]
Feature Description
Implement a "Scratch to Reveal" feature in Web Stories, allowing creators to overlay a slide with an interactive layer. Users can "scratch" this layer to reveal the underlying content, enhancing interactive storytelling and user engagement.

Alternatives Considered
Explored custom implementation using meta boxes and JavaScript within the WordPress environment. However, integrating this seamlessly within the Web Stories editor proved challenging.

Additional Context
This feature could be leveraged for various engaging storytelling scenarios, such as revealing answers in a quiz format, uncovering hidden images, or interactive advertisements.

**Comment by swissspidy** [comment]
Hi there, interesting idea!

Since this is a new feature that would need to be developed in the Web Stories format itself first, https://github.com/ampproject/amphtml/issues/39508 is the way to go.

Once the format supports a new feature, we can consider it for the Web Stories WordPress plugin.

I'm closing this issue for now until that happens.
