### ISSUE TITLE
Editor: Update wording in post-publish dialog for scheduled and private stories

### ISSUE THREAD

**Issue by AnuragVasanwala** [swissspidy/web-stories-wp#13472]
## Feature Description

Creating a **new Scheduled Story** and clicking on `Schedule` button shows `Story published.` message. In case of **Scheduled Story**, `title` and `description` of the feedback dialog needs to be corrected.

## Alternatives Considered

Not applicable.

## Additional Context

| Scenario | Current Behavior | Expected Behavior |
|---|---|---|
| Scheduled Story | <img width="1382" alt="image" src="https://github.com/GoogleForCreators/web-stories-wp/assets/75766877/6e88353c-7f53-44e0-b53e-e1e7abc2cd72"> | <img width="1382" alt="image" src="https://github.com/GoogleForCreators/web-stories-wp/assets/75766877/8cfcb58f-615a-4048-aa96-fdf6281fb3ad"> Dialog Message should be: `Your story has been successfully scheduled! <a>View story</a>.` |

**Comment by swissspidy** [comment]
The same problem exists when publishing the story as private. Then the title should be "Story published privately."

As for the description, I don't think we need to include the date. Just doing `'Your story has been successfully scheduled! <a>View story</a>.',` should be fine.

The relevant code sections:

https://github.com/GoogleForCreators/web-stories-wp/blob/b58c60cbe7228a93691becec0cbf546d580c4e3e/packages/wp-story-editor/src/components/postPublishDialog/index.js#L68-L69

https://github.com/GoogleForCreators/web-stories-wp/blob/b58c60cbe7228a93691becec0cbf546d580c4e3e/packages/wp-story-editor/src/components/postPublishDialog/index.js#L90-L93

https://github.com/GoogleForCreators/web-stories-wp/blob/b58c60cbe7228a93691becec0cbf546d580c4e3e/includes/Story_Post_Type.php#L359-L363

---

Aside / Bonus:

Instead of hardcoding the titles depending on the status, it would be nice if we could get the labels as defined during post type registration. But that requires a lot of work involving changing the post type controller, etc. to pass the labels from PHP to React. We can do that at some point in the future.
