### ISSUE TITLE
Expanded padding controls for elements

### ISSUE THREAD

**Issue by RyanNeilson** [swissspidy/web-stories-wp#13500]
## Feature Description

It would be helpful to our editors if the padding controls for any selected element offered "Top", "Left", "Right", and "Bottom" as separate options. The current "Horizontal" and "Vertical" padding options are a limiting factor in some of our designs.

For example, could the "Vertical" option include an additional lock/unlock, which when unlocked would offer "Top" and "Bottom" options?

<img width="381" alt="Screen Shot 2023-11-15 at 7 29 18 PM" src="https://github.com/GoogleForCreators/web-stories-wp/assets/32141267/f1d1949d-abfc-4980-927f-799205211a09">

## Alternatives Considered

I can't think of any alternatives that might be appropriate for this case.

**Comment by swissspidy** [comment]
Thanks for your suggestion!

Could you perhaps share a little bit more information about how you intended to use such extended padding controls?

Have you considered alternatives like positioning a rectangular shape behind a text element and using that for any stylistic purposes? Or maybe by using the border controls? Border already can be set for each direction.

I am asking because it's the first time we're getting this suggestion, and I would like to better understand the needs and possible alternatives before trying to prioritize it.
