### ISSUE TITLE
Ability to name saved styles

### ISSUE THREAD

**Issue by RyanNeilson** [swissspidy/web-stories-wp#13501]
## Feature Description

It would be helpful for clarity/collaboration if the `Saved Styles` sidebar section allowed for each saved style to be assigned a name/label. 

Possible Example:

![Screen Shot 2023-11-16 at 6 14 33 AM](https://github.com/GoogleForCreators/web-stories-wp/assets/32141267/2fb321c8-e088-4506-994c-ee85eb1d76d2)

## Alternatives Considered

I don't believe there are any existing features that might be used as an alternative.

## Additional Context

A name or label would be helpful in understanding the context in which a saved style was used. Having this context would allow saved styles to be applied consistently throughout a project.

**Comment by swissspidy** [comment]
Previously: #10968

Thanks for the suggestion. I see how this would be useful especially for teams working on stories. It would also make the feature a bit more aligned with saved templates, which already support naming. Saved colors might benefit from names as well (for brand colors etc.) but we have less space there.

Unfortunately I can't provide any information on if or when we would implement this, but I'll make sure this is on our radar 👍 

----

Implementor's note:

We would probably need to create a new post type for saved styles instead of storing them in wp_options, so that we can have proper REST methods and access control for them. It would have the side effect that certain users could be restricted from creating/renaming/deleting saved styles. However, that would be quite a big lift.

**Comment by swissspidy** [comment]
Given the required effort vs low priority I am closing this for now as a _maybelater_
