### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'updateRect')

### ISSUE THREAD

**Issue by matosdm** [swissspidy/web-stories-wp#13568]
TypeError: Cannot read properties of undefined (reading 'updateRect')
    in EditPanMoveable
    in div
    in edit__Element
    in MediaEdit
    in ImageEdit
    in div
    in editElement__Wrapper
    in EditElement
    in div
    in layout__PageAreaSafeZone
    in div
    in layout__PageAreaWithOverflow
    in div
    in layout__PageAreaFullbleedContainer
    in ForwardRef(PageArea)
    in Unknown
    in ForwardRef(WithOverlay)
    in section
    in editLayer__LayerWithGrayout
    in EditLayerForElement
    in EditLayer
    in div
    in canvasElementDropzone__Container
    in CanvasElementDropzone
    in div
    in dropTarget__Content
    in Unknown
    in div
    in dropTarget__DropTargetComponent
    in UploadDropTarget
    in CanvasUploadDropTarget
    in section
    in canvasLayout__Background
    in se
    in CanvasLayout
    in Canvas
    in EZ
    in div
    in layout__CanvasArea
    in Unknown
    in RichTextProvider
    in Unknown
    in UnitsProvider
    in Unknown
    in CanvasProvider
    in Workspace
    in section
    in layout__Editor
    in Unknown
    in LayoutProvider
    in x0
    in Unknown
    in DropTargetsProvider
    in Unknown
    in TransformProvider
    in Unknown
    in MediaProvider
    in Unknown
    in FontProvider
    in Unknown
    in StoryProvider
    in Unknown
    in SnackbarProvider
    in Unknown
    in HistoryProvider
    in Unknown
    in Media3pApiProvider
    in Unknown
    in FileProvider
    in Unknown
    in APIProvider
    in Unknown
    in ConfigProvider
    in EZ
    in Le
    in se
    in App
    in StrictMode
    in FlagsProvider

**Comment by swissspidy** [comment]
Hi there and thanks for your report! Usually we recommend reaching out about this kind of error [via the support forums](https://wordpress.org/support/plugin/web-stories/), but since you are already here, let's try to get to the bottom of this!

We just need a few more details to better understand this error:

* What were you doing in the editor when this error occured? Any steps to reproduce or even a video would be extremely helpful.
* What version of the plugin are you using?
* Which browser are you using?

----

I'm a bit surprised about the error message as we added optional chaining to the `updateRect` call back in #5542, so this shouldn't really happen:

https://github.com/GoogleForCreators/web-stories-wp/blob/4e7bc596ad008f4751460f6538172bf469186a6d/packages/element-library/src/media/editPanMoveable.js#L61

**Comment by swissspidy** [comment]
@matosdm Just checking in here, is this still happening for you?
