### ISSUE TITLE
Dashboard: Add input to change publisher name

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#9042]
## Feature Description

In the dashboard, there is currently an option to update publisher logo. However, there is no way to update the publisher name. This default's to the site name. The publisher name could be different from the site name, so we should give the user the option to change this in the dashboard.

**Comment by spacedmonkey** [comment]
Now that publisher logos are stored a story level. See https://github.com/google/web-stories-wp/pull/8946. There is also a question if like publisher logo, we should have a global publisher name but allow for an override at the story level. 

Extra context. https://xwp.slack.com/archives/C013J2EGH8R/p1631703824049800

**Comment by swissspidy** [comment]
cc @gajasinski for product decision on this

**Comment by gajasinski** [comment]
Seems like we should keep these two (logo and name) aligned. I'm fine making this a P1

**Comment by swissspidy** [comment]
So to clarify, this would mean:

* Add "Publisher Name" text box to the Settings page
* Add "Publisher Name" text box to the Document Panel in the editor (under "Publishing")

**Comment by gajasinski** [comment]
@agingoldseco ^^

**Comment by agingoldseco** [comment]
I see no issues with this, like the idea! I think the box should go under the "author" box in in the Publishing panel, but is it also a dropdown like the other inputs there? Not sure how/if alternative publisher names would get stored

**Comment by swissspidy** [comment]
Not sure we really need a dropdown to choose between alternate publisher names.

I think a simple text box should suffice.

**Comment by agingoldseco** [comment]
Okay, cool—think my comment was while I was questioning the overall future look of text boxes in the editor. Does this need a mockup? I just envision a text box like the attached that says "Publisher Name" underneath "Author"

<img width="293" alt="Screen Shot 2021-11-08 at 6 31 44 PM" src="https://user-images.githubusercontent.com/90645922/140835063-ffb19606-65a3-4dfd-8113-7d300a35cdec.png">

**Comment by swissspidy** [comment]
Yeah I don't think this necessarily needs a mockup as it's really a simple change.

It's just important that the field is pre-filled with the publisher name configured in the settings.

The big problem with our text boxes right now is that they don't have labels (which is really bad for accessibility!).

So with the publisher name filled in you have no idea what the field is for:

![Screenshot 2021-11-10 at 11 16 16](https://user-images.githubusercontent.com/841956/141094803-945f0db1-06fd-4b95-8ad2-14bb0e9211cf.png)

That's why I pinged you on the #4706 ticket, to see how we can fix this accessibility issue.

**Comment by agingoldseco** [comment]
Ah, just saw this after answering that other ticket—that's why I was almost hoping a dropdown was needed here so we could avoid this issue (lol). Our design system actually has labels for above fields, but previous designers didn't implement those. Miina and I speculated about whether we should get change the design system to reflect that, but I've been concerned about this accessibility issue. 

I think it's okay to put this field in with the in-field label for now, since it doesn't auto-populate, but soon I think I'll need to inventory where the accessibility unfriendly text fields are and come up with blanket solution.

**Comment by swissspidy** [comment]
> I think it's okay to put this field in with the in-field label for now, since it doesn't auto-populate

It _does_ auto-populate with the publisher name from the settings, which defaults to the site title. That is needed because the publisher name is a requirement.

**Comment by agingoldseco** [comment]
OH, okay. Then this may be a time to just put a label on there that already exists in the Storybook. We could add it to others later, but it's necessary for this if the description is obscured. One less thing we have to worry about being accessible. 

<img width="789" alt="Screen Shot 2021-11-10 at 1 23 01 PM" src="https://user-images.githubusercontent.com/90645922/141172263-f021ccf3-e974-442d-b145-b2e3a3fff0ef.png">
