### ISSUE TITLE
Design System: Change Dropdown placement if there's not enough space

### ISSUE THREAD

**Issue by samwhale** [swissspidy/web-stories-wp#9049]
## Bug Description

Dropdown can be hidden if it's located too low on the screen. We could update the placement similar to #8822.

## Expected Behaviour

Dropdown options should always be visible

## Steps to Reproduce

Testable once #9048 is merged
1. Enable the taxonomy feature flag
2. Go to the categories and tags panel in the document panel
3. Add like 7 categories
4. Click on the `Add New Category` button
5. Scroll the page all the way down
6. Click on the `Parent Category` dropdown. See that the dropdown gets cut off.

## Screenshots

![image](https://user-images.githubusercontent.com/22185279/133680298-779da1dc-966c-4fde-af86-e89454787a6d.png)

## Additional Context

- Plugin Version: 1.12.0-alpha
- WordPress Version: 5.8.1
- Operating System: Mac OSX 11.5.2
- Browser: Chrome

**Comment by BrittanyIRL** [comment]
(@csossi - since taxonomies is behind a flag still, this is mainly going through QA for regression - if you can just make sure that dropdowns on the editor and dashboard are functioning like normal then we're good. I also did this when I reviewed, I know you are under the weather so if you don't have time for this that's ok just let me know and we'll do some more testing ourselves and move forward)
