### ISSUE TITLE
Custom Page Templates: Try `html-to-image`

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9094]
## Description

Following work done in default page templates to use screenshots instead of rendering previews of each page, we should expect the same as users from custom page templates. 

There's several instances of doing this in the editor already with the carousel page previews and on the canvas with zoom, so let's start there.

Assuming that works, tie this update into the updated component(s) used in the static version of the default page templates.

**Comment by BrookeGraham** [comment]
Turns out using html-to-image (or similar) would negatively impact performance. In order to grab or create the images we would first have to render the component. In this case, since we do not have access to custom templates ahead of time, we would still need to load the entire template node before converting to an image. Then we would need added work ie. importing html-to-image, running the function to create an image, then we would need to store and possibly cache these images. Only then would we eventually _possibly_ see some performance improvements, however the added cost would like cause an initial drop in performance initially. I do not recommend implementing this html to image feature for saved templates.

**Comment by swissspidy** [comment]
Could we use html-to-image to generate the image at the time of _saving_, i.e. when the user saves a custom page template we also generate & upload the image? So we'd save the template together with the image. And then when loading the custom page templates we just load all the images we've previously generated.

**Comment by BrookeGraham** [comment]
Great idea. I think that could work nicely. We would still have to figure out a way to generate images for previously saved templates. 🤔

**Comment by BrittanyIRL** [comment]
oh that would be fun to explore! Let's keep this ticket as discovery to figure out a game plan for that. would be a great add for 1.15 (dec release)

**Comment by maxyinger** [comment]
at what point are we generating the image for the carousel page previews?

**Comment by BrittanyIRL** [comment]
> at what point are we generating the image for the carousel page previews?

after the initial node is created so that an image can be produced.  (checkout `components/carousel/pagepreview`)

**Comment by BrookeGraham** [comment]
To me it makes sense to add use html to image when the user creates a template. BUT how do we generate the images for the ones already saved? That would mean something like using the implementation we currently have in order to generate the node which we would use to create the image. Then we could upload those images and save on the BE somewhere (or upload to s3 or where we currently store images) Then we could say something like, IF we already have all the saved images make an api call to grab them then it would be possible to use this new saved images component that shows those images. HOWEVER if we don’t have the images yet, render the old saved templates component, and do the whole generate the image, upload, etc. 🧐

**Comment by maxyinger** [comment]
> So we'd save the template together with the image. And then when loading the custom page templates we just load all the images we've previously generated.

> HOWEVER if we don’t have the images yet, render the old saved templates component, and do the whole generate the image, upload, etc

Yea I think this all makes sense. it's just a question of where would we be saving the image. 3 options come to mind:
1. Saving the base64 encoding to localStorage
2. Storing base64 encoding on a field in the custom template object (have no idea how viable this is)
3. Storing generated image blobs in indexedDB

Wondering if either option 1 or 3 would be viable for a perf optimization for the carousel thumbnails to not have to generate every page every time 🤷‍♀️ .

thoughts @swissspidy @miina ?

**Comment by maxyinger** [comment]
I guess another metric that could help too is collecting data on how many custom templates a typical user has. I'm assuming we're not reporting that now, but might be worth tracking

**Comment by BrookeGraham** [comment]
> it's just a question of where would we be saving the image. 3 options come to mind:
> Saving the base64 encoding to localStorage

- I am not sure how many saved templates the average user has nor am I familiar with how much we are currently using localStorage, but would it be possible that we fill up localStorage? Probably not, since most browsers allow a lot of storage, (250MB - 1.1GB or more) but just asking. 
- If in incognito mode, would this still be viable?  _localStorage data for a document loaded in a "private browsing" or "incognito" session is cleared when the last "private" tab is closed._
- Images would have to be recreated every time the localStorage is cleared or the user is on a different device which means we would never be able to fully remove the "old way" of rendering the templates as thumbnails. There is no guarantee we will have access to those images.

> Storing base64 encoding on a field in the custom template object (have no idea how viable this is)

Seems like a nice solution, we can guarantee a user will always have access to the images. So moving away from the "old" way of rendering the template would be possible. However, we would have to figure out a way to backfill for templates that are already saved. 

> Storing generated image blobs in indexedDB

I can't remember what os we support, but I did find [this](https://developers.google.com/web/fundamentals/instant-and-offline/web-storage/indexeddb-best-practices#not_everything_can_be_stored_in_indexeddb_on_all_platforms) on indexedDB _Safari on iOS, in particular, cannot store Blobs in IndexedDB._ I believe there are work arounds but just wanted to note it.

**Comment by swissspidy** [comment]
Why not just upload the file to the server...? 🤔 

I don't see why this would need to be base64 encoded, nor why this should be stored locally in localStorage or IndexedDB. That doesn't make sense to me tbh.

Backfilling shouldn't be difficult. We just need to run `html-to-image` if the image is missing and upload to the server. While this happens, simply display the "old" "live" preview, or perhaps even some placeholder.

**Comment by BrookeGraham** [comment]
> Why not just upload the file to the server...? 🤔

I guess that is what this thread is trying to discuss. Going this route would require changes from pods other than the Pea Pod. So I am wanting to make sure that this option looks good to everyone. Especially since I don't know the scale of custom templates and if that would become (or is) an unreasonably large amount of data for us to store. 
 
> I don't see why this would need to be base64 encoded, nor why this should be stored locally in localStorage or IndexedDB. That doesn't make sense to me tbh.

Provided as an alternate solution if we didn't want to take route of adding these images to  custom templates object. 

> Backfilling shouldn't be difficult. We just need to run html-to-image if the image is missing and upload to the server. While this happens, simply display the "old" "live" preview, or perhaps even some placeholder.

Agreed. This would mean that we would do both, html to image on save _and_ html to image when displaying the "old" live version because we don't yet have the image on the custom templates object. At least until all custom template images have been back filled. Then we could fully eliminate the "old" live template thumbnails.

**Comment by BrittanyIRL** [comment]
So, we wanna move forward with saving each custom template on creation ('save') as an image and if an image doesn't yet exist for a custom template rendering the preview as we do today and then saving an image of it to back fill? 

@swissspidy where/what level would you like this to be stored? Feels like it should be available at the plugin level for users within that instance of WordPress. I'll scope out an epic but i want to make sure I'm writing legible tickets.

**Comment by swissspidy** [comment]
The template image would be uploaded to WordPress just like any other image/video/publisher logo/video poster/etc. We'd make sure to hide it from the actual media library of course.

**Comment by BrittanyIRL** [comment]
> The template image would be uploaded to WordPress just like any other image/video/publisher logo/video poster/etc. We'd make sure to hide it from the actual media library of course.

🤔  would this be something we'd need user buy in to let us do?

**Comment by BrookeGraham** [comment]
>The template image would be uploaded to WordPress just like any other image/video/publisher logo/video poster/etc. We'd make sure to hide it from the actual media library of course.

Also curious if this would eat into the amount a storage the user is allocated? (To be honest not 100% sure how that works)

**Comment by swissspidy** [comment]
@BrittanyIRL What do you mean?

We upload tons of files to WordPress already, for example all generated video posters or the story poster image. This would be no different.

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL What do you mean?
> 
> We upload tons of files to WordPress already, for example all generated video posters or the story poster image. This would be no different.

It just felt weird to me uploading these images that the users wouldn't really consider images without their permission. If i were a user and I went to my media gallery after saving some templates I would think it's odd to see them in my media. I'm happy for it to be a non-issue/bad question, just figure it's a good time to ask.

**Comment by swissspidy** [comment]
> If i were a user and I went to my media gallery after saving some templates I would think it's odd to see them in my media.

That‘s why I said we would hide the images from the media library. So you don‘t see them there.

**Comment by BrittanyIRL** [comment]
> > If i were a user and I went to my media gallery after saving some templates I would think it's odd to see them in my media.
> 
> That‘s why I said we would hide the images from the media library. So you don‘t see them there.

Cool 👍  I'm good then. Thank you for spending the time on this. I'll go make an epic.

**Comment by BrittanyIRL** [comment]
New epic created for further work on this, closing!
