### ISSUE TITLE
Video Trimming: Prompt the user that Video Encoding needs to be enabled to use the Trimmer

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9191]
## Feature Description

In order for Video Trimming to be enabled, the user must have "Video auto-optimization" enabled in their settings. There should be some sort of cue/prompt to indicate this to the user, or alternatively, this dependency could be removed.

As @samwhale reported in the bug bash, it was challenging for him to understand how to enable the video trimming functionality without this prompt.

**Comment by swissspidy** [comment]
It‘s not possible to remove this dependency. Video optimization **must** be enabled for this to work.

**Comment by spacedmonkey** [comment]
There is a already a dialog that shows, the first time a user tries to optimize a video, encouraging them enable it. This should show if you try and trim a video. See https://github.com/google/web-stories-wp/issues/6087

**Comment by swissspidy** [comment]
We can't just show exactly that same dialog 1:1 though.

The dialog in #6087 says: "video optimization in progress. wanna disable?"

Here we'd need the opposite: "hey you can't do this right now, enable video optimization first"

Related: #7473

**Comment by swissspidy** [comment]
The primary bug here is that the "Trim video" quick action button was shown despite video optimization being disabled. This should not be the case.

There needs to be a check for `isTranscodingEnabled` here:

https://github.com/google/web-stories-wp/blob/89ea2c167515435f6d1d7a6258a0af85d12ebe1e/packages/story-editor/src/app/highlights/quickActions/useQuickActions.js#L473-L489


Edit: Maybe I spoke too early

**Comment by swissspidy** [comment]
@samwhale could you provide more details about what happened?

**Comment by samwhale** [comment]
Sure! This is more of a UX idea:

- I opened my app, I already had `Video Optimization` turned off in my dashboard settings
- I navigated to the editor and added a video from the media menu
- Opening the `Video Settings` panel I expected to see the `Trim` button but it wasn't showing (because the setting wasn't enabled)

I was thinking that it would be nice to have some text in this panel informing the user that trimming is possible if that setting is enabled. There could even be a checkbox like in the checklist to do it right there:
<img src="https://user-images.githubusercontent.com/22185279/135500647-e1b0d20c-6de7-4e30-903d-ca097ba39af2.png" height="400px" />

**Comment by swissspidy** [comment]
Related: #12038

**Comment by swissspidy** [comment]
Closing in favor of #12038
