### ISSUE TITLE
"Replace media/background" quick action should actually replace

### ISSUE THREAD

**Issue by dreamofabear** [swissspidy/web-stories-wp#9196]
## Feature Description

Expected: The "Replace media/background" quick actions replaces the currently selected media while preserving position and size (and respecting the new media's aspect ratio)

Actual: The "Replace media/background" quick actions just focuses the media panel

## Alternatives Considered

N/A

## Additional Context

This would make templates more usable by making it much easier to swap out the stock images.

Originally reported by `mludwig@` who was assisting an external user.

**Comment by BrittanyIRL** [comment]
I know we talked about this - I can't find the issue reflecting it. I did find this thread in slack: https://xwp.slack.com/archives/C01ESBB8ZN1/p1623188613096600

So yes, it _should_ replace but that's rather complicated because is the user expecting to replace the media in the same way they originally did? What's that mean if they used a third party media? Is it new media so we should open the modal to upload something new? 

This needs UX before any action can be taken on it.

**Comment by dreamofabear** [comment]
Makes sense. 

Quick strawman: 
- "Replace media" should cause the editor to enter an obvious "replace" mode, where the next media insertion will replace the selected element
- Deselecting the element will exit this mode
- The mode could be indicated with a specially styled border and overlay/scrim over the selected element that says "Replacing..."

/cc @aaskedall @agingoldseco

**Comment by spacedmonkey** [comment]
Clicking that button, I would expect the WordPress media dialog ( media Picker ) to open. From there, after I select an image, it would replace the existing image.

**Comment by dreamofabear** [comment]
> Clicking that button, I would expect the WordPress media dialog ( media Picker ) to open. From there, after I select an image, it would replace the existing image.

That won't work for 3P media but sounds like a promising cheaper option.

**Comment by BrittanyIRL** [comment]
@choumx  So is the media dialog (media picker) what we want to have happen for replacing media?

**Comment by dreamofabear** [comment]
I think that's a solid first pass, but I'll defer to UX if they have other thoughts.

**Comment by BrittanyIRL** [comment]
@agingoldseco @aaskedall Curious if you feel good with us moving forward with setting the 'replace media/background' action to open the media dialog?

**Comment by swissspidy** [comment]
FYI, a user has just [reported](https://wordpress.org/support/topic/replace-media-tool-not-working/) this issue as well.

> the replace media button only directs me to my wp library, not replacing the image in anyway after choosing at all, only inserting the image without the prior properties

Screencast showing their confusion: https://www.awesomescreenshot.com/video/5576344?key=614ab02bec2572706dbe96fa1b242f21

It looks like they expected the "Replace media" button to activate some sort of "media replacement mode", where the next image they clicked on in the library would replace the current one.

That might be a viable alternative to the approach suggested above.

Thoughts?

**Comment by samwhale** [comment]
This feature is working as designed. The copy implies different functionality, but the designs have the same implemented functionality as shown in [this board](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=6310%3A569093).

When this was being implemented, we talked about how 'replacing' media wouldn't work without some more design work. Implementing it as a new feature would need:
1. A way to tell the user they’re currently replacing media 
2. Blocking all other actions
3. An escape hatch in case the user doesn’t want to replace the media anymore

A modal would be a good way to handle this (similar to the other modals in the app). If we don't block the user from doing anything else then we could run into this scenario:

1. user has a bg image & clicks the action
2. bg img data gets saved and they get redirected to the media panel
3. User decides to go do something else - update a link, add new text, etc.
4. they come back and click the panel for another image (forgetting they had selectd to replace), but then it replaces the old bg image

---

IMO the issue here is that the copy implies different functionality than what exists, but the fix is not to add a new feature. It would be to update the text or to remove the button entirely.

We can always add a feature in the future for media replacement though ✅

**Comment by BrittanyIRL** [comment]
Thanks for sharing your insight on this one @samwhale since you worked on it initially! 

Let's put a pin in this until Will gets back from PTO. I'll add a reminder to my notes to bring it up next week.

**Comment by dreamofabear** [comment]
> This feature is working as designed. 

Yup, to clarify this is not a bug but an enhancement. 

It sounds like we're all on the same page that either a "replace mode" or showing the WP media dialog would work here, with the former being more complex but also more robust.

**Comment by BrittanyIRL** [comment]
Per discussion between @choumx  and @aaskedall  we're going to go the modal route. So you click on replace media and the dialog will open, the media selected from the dialog will replace the existing media. If the user closes the dialog without selecting new media then the existing media will stay put.

**Comment by samwhale** [comment]
I'm assuming the `Needs More Info` and `UX Needed` labels aren't needed anymore, right? :)

**Comment by csossi** [comment]
Verified in QA
