### ISSUE TITLE
Zoom jumps to "Fit" view after adding a new element

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#9207]
## Bug Description

Original report: https://wordpress.org/support/topic/experiencing-lag-bugs-while-editing-stories/

The zoom jumps to "fit" view any time you add a new element (media, text, shape) to the page.

## Expected Behaviour

The zoom view setting should remain on the current view set after adding a new element.

## Steps to Reproduce

1) Change the zoom to 100%, 200%, or Fill.
2) Add a new element like image, video, text or shape. 
3) Notice the view jumps to Fit. 

## Screenshots

https://user-images.githubusercontent.com/66372350/135301671-b7307638-51bd-4f10-969f-6b83ee2fdfc2.mov

## Additional Context

- Plugin Version: 1.11.0
- WordPress Version:
- Operating System: macOS
- Browser: Chrome

**Comment by swissspidy** [comment]
cc @barklund @miina

**Comment by miina** [comment]
@swissspidy This was a design decision since adding elements in Zoom was not the intended behaviour, there was quite a bit of discussion around that.

E.g. if the user is Zoomed in then there would be inconsistency between dragging an element to canvas vs clicking an element to add -- the dragged element would be much smaller unless that's also zoomed, but if we'd Zoom the element being dragged, then it could cover the whole screen while dragging.
There were also some doubts about the placement of the added image.

That's probably something that would good if @aaskedall could revisit.

**Comment by miina** [comment]
Tagging @gajasinski and @agingoldseco here as well to get feedback about the expected behaviour (see the previous comment).

**Comment by gajasinski** [comment]
Do we have any other instances of this arising? For now, agreed with @miina - I think this behavior is OK and would not prioritize this work. @agingoldseco - can you weigh in?

For ref - the experience described by the user is valid in Google Slides (adding elements while zoomed keep the user zoomed and adds the element). I can see value to both approaches.
