### ISSUE TITLE
Block: `getAuthors()` deprecation notice

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#9240]
## Feature Description

When using the story picker in the web stories gutenberg block, the following noticed is displayed. 

```
react_devtools_backend.js:4049 select( 'core' ).getAuthors() is deprecated since version 5.9. Please use select( 'core' ).getUsers({ who: 'authors' }) instead. 
    at SelectStories 
```

See screenshot for full details. 
<img width="1904" alt="Screenshot 2021-10-04 at 16 45 49" src="https://user-images.githubusercontent.com/237508/135882467-52ed3cac-c1f1-4b80-801f-2ff13afac859.png">

This change happened upstream here https://github.com/WordPress/gutenberg/pull/33725

**Comment by swissspidy** [comment]
Relevant issues/PRs:

Here's where the post author dropdown was updated to use `getUsers` in Gutenberg: https://github.com/WordPress/gutenberg/pull/33695

Here's where `getUsers` gained the ability to fetch with `context=view` so that it can be used for things like the author dropdown: https://github.com/WordPress/gutenberg/pull/32961

I asked for some clarification on https://github.com/WordPress/gutenberg/pull/33725#issuecomment-934382234 and am curious to hear what the team says.

**Comment by spacedmonkey** [comment]
Until we hear back from the Gutenberg team on this one, I think we can consider this one blocked. I agree with you, that doing version checks is not really the best solution here.

**Comment by spacedmonkey** [comment]
@swissspidy What is happening with this ticket?

**Comment by swissspidy** [comment]
No action needed for now

**Comment by spacedmonkey** [comment]
Isn't the message in Gutenberg not wrong. We shouldn't be pushing people to be using who param.

**Comment by swissspidy** [comment]
Yes and no. I mentioned that in https://github.com/WordPress/gutenberg/pull/33725#issuecomment-939497936 as well. But since Gutenberg also supports WP 5.8, `who` still needs to be used.

Something to figure out on the Gutenberg repo though.

**Comment by swissspidy** [comment]
We can now remove compat code in places like `\Google\Web_Stories\REST_API\Stories_Users_Controller::filter_user_query()` and `getAuthors()` (found twice, in `wp-dashboard` and `wp-story-editor`)
