### ISSUE TITLE
Layer grouping

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9244]
Discussed and requested by design in conjunction with #8983 but isolated to make sure details are attended to accordingly. 

https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor-Sprint-Feature-Level-Designs_?node-id=9935%3A421370

![Screen Shot 2021-10-04 at 12.01.08 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/dccbfc16-9414-4bd5-b722-08d8cfb3d1c1)

## Acceptance Criteria

- [ ] Group should be moved as one element.
- [ ] Group should be aligned as one element.
- [ ] You can enter the group by double-clicking.
- [ ] Grouping/Ungrouping should be possible from the Canvas RCM and Layers Panel context menu.
- [ ] Visual representation of the group in the Layers Panel.
- [ ] You can collapse/expand the group in the Layers Panel.
- [ ] TBD: Nested groups.
- [ ] TBD: Locking the whole group.
- [ ] TBD: Locked element inside group vs group selection bounding box.

## Other notes 

Grouping layers is going to impact keyboard users because right now the layers panel is hidden for keyboards as all functionality is mirrored in keyboard shortcuts. The accessibility of the layers panel will need to be reconsidered ahead of this functionality getting added to the layers panel.

**Comment by swissspidy** [comment]
FYI there was already a ticket for this. Closed it as a duplicate.

**Comment by agingoldseco** [comment]
For the moment, it seems the only additional (or updated) acceptance criteria to come from our meeting are:

- User can drag other layers into a group in the layers panel
- User can ungroup layers by right clicking on the group in the canvas or layers palette
- Groups can be locked/unlocked

I also looked at Canva. Once objects are grouped, you can't move the layers in that group individually at all unless you ungroup. But they also don't have a layers palette (in the free version, at least). They do, however, allow you to make a group out of two groups and I believe it just flattens all the elements into a single group instead of nesting them. Maybe that would work for us too. Would it make sense to not make big decisions on these things until you get to some proof of concept work to see what's feasible or technically more difficult than you thought?

**Comment by merapi** [comment]
> Maybe that would work for us too. Would it make sense to not make big decisions on these things until you get to some proof of concept work to see what's feasible or technically more difficult than you thought?

Yes, I agree.
