### ISSUE TITLE
Taxonomies: Available categories not updating after editor is loaded

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9282]
## Feature Description
Originally reported by @barklund 

Categories don’t reload while in the editor. I know that’s pretty much by design, but in this context (where we’re all editing categories), it would be nice. Maybe have an “update categories” link somewhere to refresh? You might be editing a story, realise that you want to reorganise categories, go out to the category section to do so and the when coming back to the story, you want to reload just the category tree. It could just be a small button with a reload icon.
[Brittany] +1, this would be great too for when searching categories

**Comment by BrittanyIRL** [comment]
@littlemilkstudio will you weigh in here and point this?

**Comment by maxyinger** [comment]
a small button to refresh the categories shouldn't be bad. maybe a 2 pointer. updating the search to hit the backend instead of the current pulled down categories is probably a 3 pointer.

All depends on the UX we want here. In the description, it sounds like you and Morten are proposing different solutions to the same problem?

Should we run the problem by Andrew or Amy to weigh in on exactly what behavior they want? then accurately scope and describe the feature request?

**Comment by swissspidy** [comment]
Seems like a low prio use case to me IMO. One can just reload the editor.

**Comment by BrittanyIRL** [comment]
Let's pause on this one and see if it remains an inconvenience/tackle it when there's a lull.

**Comment by maxyinger** [comment]
> Seems like a low prio use case to me IMO. One can just reload the editor.

Completely agree. This feels more relevant to Bug Bash use of the feature than typical user use.
