### ISSUE TITLE
Checklist thumbnail to show more affected pages has no action

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#9350]
## Bug Description

As originally reported in this support topic https://wordpress.org/support/topic/checklists-show-more-button-not-showing-more, there is no action when clicking on the thumbnail to show more affected pages. 

## Expected Behaviour
To show more pages affected by the checklist warning / drive the user to those affected pages.

## Steps to Reproduce

Create a story with **more than 4 page**s without text
Open checklist
Click on the + 5 thumbnail to show more pages 
Note inaction 

<img width="307" alt="Screen Shot 2021-10-11 at 11 58 00 AM" src="https://user-images.githubusercontent.com/66372350/136820888-5a60a49f-e88a-4626-a027-938de7ec0a1a.png">

## Additional Context

- Plugin Version: 1.12.0
- WordPress Version:
- Operating System: macOS
- Browser: Chrome

## Feature Description
(Updated Dec 15, 2021) 

We're going to add a toggle to expand the thumbnails to see all as a grid. The toggles will persist (just like the panel accordions) for the duration of the user's session until the toggle disappears (all issues or enough issues are resolved for it to go away). 

Figma link: https://www.figma.com/file/V452QsH7ZJhwmAuHtC0xOj/Pea-Pod-Features?node-id=33%3A4300 

Description from @agingoldseco  from [slack thread](https://xwp.slack.com/archives/C0134J07HV3/p1639591784046700): 
> User can click the +8 button OR "Expand" to open the other pages but also has the flexibility to collapse it if they want
Expand/Collapse + arrow convention can be the same as the new pages carousel one
If the user expands the cards, they can stay expanded for the duration of their session even if they close the checklist
My thinking here is that people with small screens will likely have to close the checklist a lot to address checklist issues cause it's in the way of the canvas

<img width="889" alt="Screen Shot 2021-12-14 at 11 31 48 AM" src="https://user-images.githubusercontent.com/10720454/146263060-05addf06-d004-45cd-a165-40cae9386c73.png">

As far as keyboard interaction goes with the dual 'click +8 button or "expand" to open' - since the "+8 button" is actually not a button let's just have the next focusable element after the last actual button in the initial grid row (that would be the 3rd column) just drop to the 'expand' button since that's a real button and it's redundant to have the same button in the tab order twice.

## Acceptance Criteria 
- toggle added to checklist per the above description and details 
- component added to storybook within card structure
- relevant tests 
- keyboard accessibile

**Comment by swissspidy** [comment]
/cc @BrittanyIRL @aaskedall 

I know we implemented it this way on purpose. The "+ 5" is just to tell users how many more affected elements/pages there are. So changing that to expand the list on click seems more like an enhancement.

**Comment by BrittanyIRL** [comment]
Yeah this is intentional, this would be an enhancement - open to ideas on how to best "expand" the list. Off the top of my head, showing them in subsequent rows or a carousel make sense.

**Comment by BrittanyIRL** [comment]
@choumx @gajasinski  @agingoldseco - is this a feature you would like to see? If so, we should add it to the roadmap and prioritize some design.

**Comment by gajasinski** [comment]
I think it could be helpful, particularly since we know there's a lift on creating these stories. However, I get worried about additional text/rows making content difficult. I would not be opposed to spending a cycle to see if we could improve the UI.

**Comment by dreamofabear** [comment]
Slightly dissenting opinion: For checklist errors in general, I think showing three pages to fix at a time should be enough. Maybe we can just make the "+5" indicator look less like a button?

If the concern is that creators don't want to fix the first 3 pages shown on a checklist item, perhaps we could support an "ignore" or "acknowledge" function. This might be useful for non-critical checklist items like "not enough text".

**Comment by BrittanyIRL** [comment]
>  Maybe we can just make the "+5" indicator look less like a button? 

I think this would go a long way! 


The 'ignore' or 'acknowledge' functionality is something that was floating back and forth winter 2020/spring 2021 - we landed on not doing it because these should be things that aren't ignored. That said, i could see users being frustrated by not wanting to fix say the first 2 in a series of 12 image related issues and wanting to see the rest of them. Devil's advocate says, if they aren't going to fix those first 2 they probably won't also fist the other 10?  Think that this just needs some UX magic to maybe do some sort of toggle to expand all issues but by default not impact the spacing.

**Comment by agingoldseco** [comment]
Worse than the +X looking like a button is the cursor changing to a hand over it. I actually also think it should expand the other pages into a grid or carousel, at the risk of creating more scroll—it's the user's choice to open the other pages in the first place because they want to see them, on some level understanding that risk. But I agree with George that it might be worth spending some additional time on this—maybe we want to let people collapse the pages again, or allow individual pages to be marked as acknowledged for people who _really_ like checking things off a list. Overall, I err on the side of giving the user a simple choice of learning what's behind that number rather than continuing to hide the pages.

**Comment by BrittanyIRL** [comment]
Perhaps this would be a good thing to get on the roadmap?

**Comment by agingoldseco** [comment]
@BrittanyIRL I think so—even if it ends up being a simple change, would be good to give it real consideration.

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #10058.

1. Created a story with the following elements:
    Element with link too big
    Element with link too small
    Image element missing alt
    Image element resolution
    Text contrast too low with page background
    Page too little text
    Page too many links
    Page too much text
    Text font size too small
    Video too long
    Video no captions
    Video no description
    Video no poster
    Video element resolution too low
2. Clicked on checklist
3. Clicked on Design
4. Clicked on expand/collapse
5. Clicked on +[number of panels]
6. Added/removed panels



https://user-images.githubusercontent.com/96055551/149771644-c7d5f5d6-8cf3-4e6d-9d8a-f579f8f4b4d3.mp4
