### ISSUE TITLE
Issue with ampersand "&" in title 

### ISSUE THREAD

**Issue by CrystalOnScript** [swissspidy/web-stories-wp#9408]
## Bug Description

I placed an ampersand "&" in the title and the editor replaced it with the `&amp;` html entity 

## Expected Behaviour

I would like my & to stay an & 

## Steps to Reproduce

Place an "&" into your story title, save your story, then return to the editor 

## Screenshots

![Screen Shot 2021-10-13 at 2 06 06 PM](https://user-images.githubusercontent.com/23297417/137212946-2a1643df-1b64-4f52-ada9-24bc585a30a0.png)
![Screen Shot 2021-10-13 at 2 05 30 PM](https://user-images.githubusercontent.com/23297417/137212949-d3fa89ba-cd9f-4d5e-b684-f70dea574d38.png)

**Comment by swissspidy** [comment]
Thanks for your report Crystal!

Looks like it's related to how WordPress encodes/decodes HTML entities when saving and the user not having many permissions. I can see the same issue in the WordPress block editor:

![Screenshot 2021-10-13 at 23 39 58](https://user-images.githubusercontent.com/841956/137216367-33b1b7bf-40d1-4188-a727-d200a2dda487.png)

Things look correct on the "All Stories" / "All Posts" page, so that's something.

Should be possible to get this fixed in the editor and dashboard too.
