### ISSUE TITLE
Settings: publisher logo upload button uploads one less image

### ISSUE THREAD

**Issue by mohdsayed** [swissspidy/web-stories-wp#9499]
## Bug Description

When uploading more than one images for publisher logo under dashboard settings, the first image doesn't get saved.

## Expected Behaviour

It should save all the uploaded images.

## Steps to Reproduce

1. Go to dashboard settings 
2. Click on "Upload Logo" button and choose more than 1 images.
3. Refresh the page and see

## Screenshots

https://imgur.com/TcG0bp1

## Additional Context

- Plugin Version: 1.14.0-alpha.0
- WordPress Version: 5.8.1
- Operating System: Mac
- Browser: Chrome

**Comment by swissspidy** [comment]
I wonder if that's a regression introduced in my refactoring a couple of weeks ago 🤔

**Comment by BrookeGraham** [comment]
I haven't been able to pin point this issue on the FE.

> I wonder if that's a regression introduced in my refactoring a couple of weeks ago 🤔

 @swissspidy  which pr where you referring to? I can take a look there this afternoon. It seems only the first upload image is actually being saved. Though each image is created and gets a successful response from the api 🤷🏻‍♀️

**Comment by swissspidy** [comment]
That was in #9101

**Comment by BrookeGraham** [comment]
@swissspidy 

We are pretty certain this issue stems from an issue in the BE. Though I can't pinpoint exactly where the bug is it seems there is likely an issue with the `id` being created for each uploaded logo. When we make the api call for each image, each image is created then we get a successful response from the api,  it's all good. All images show up on the page so long as you don't refresh the page. However, if you try to delete one of the non-last logos from the batch upload you'll get a 400 error with this `response: {"code":"rest_invalid_id","message":"Invalid ID","data":{"status":400}}`  Similarly if you try to make one of the non-last images the default, you get the same error message.  BUT once you manually refresh the page most of the uploaded files disappear, only the last image of the new logos upload batch was saved correctly, or at least is fetched correctly.

**Comment by swissspidy** [comment]
Hmm looks like some race condition when updating the list of publisher logos

**Comment by swissspidy** [comment]
#9572 should fix this. PTAL.

**Comment by csossi** [comment]
Verified in QA
