### ISSUE TITLE
Layer panel: Remove scrollbar when the layer panel is max height

### ISSUE THREAD

**Issue by samwhale** [swissspidy/web-stories-wp#9542]
## Bug Description

Expanding the layer panel to its maximum height makes a scrollbar appear for no reason.

## Expected Behaviour

The layer panel should only show a scrollbar if there are too many layers to display on the screen.

## Steps to Reproduce

Expand the layer panel all the way up.

## Screenshots

<img src="https://user-images.githubusercontent.com/22185279/138967976-0fe3241f-a5ca-477a-863d-6925c6fec89c.png" height="450px" />

## Additional Context

- Plugin Version: 1.14.0-alpha
- WordPress Version: 5.8.1
- Operating System: MacOSX Sierra
- Browser: Chrome

**Comment by BrookeGraham** [comment]
This issue is due to a `maxHeight` override prop being sent to the resize. We are currently sending the `MAX_HEIGHT_DEFAULT`  as that override which has a value of `999999999` Do we want to set the max height to 70% of the inspector (like other default values) or should we also the layers panel to expand all the way to the top aka the full height of the inspector (minus the height of the Design | Document tabs)? 

This:
<img width="165" alt="Screen Shot 2021-10-29 at 1 56 34 PM" src="https://user-images.githubusercontent.com/1820266/139494797-88e95240-1ed3-496a-8245-c9ec66555329.png">

Versus:
<img width="165" alt="Screen Shot 2021-10-29 at 1 58 59 PM" src="https://user-images.githubusercontent.com/1820266/139494831-b2ad414e-999e-4d64-9ce6-712e0e971899.png">

**Comment by samwhale** [comment]
Yeah! So the idea is that the maximum height should fill the space just under the design/document header bar.

**Comment by csossi** [comment]
Verified in QA
