### ISSUE TITLE
Decoupling: Package for common utility functions

### ISSUE THREAD

**Issue by mohdsayed** [swissspidy/web-stories-wp#9639]
## Feature Description
Sometimes there is a need to share some utility functions between packages, for instance, `snakeToCamelCaseObjectKeys` is required to be used in both `wp-*` integration packages for making the API responses of the API callbacks camel case. Currently, the available options are to either duplicate the code or move it to `@web-stories-wp/design-system`. 

## Additional Context

https://github.com/google/web-stories-wp/issues/2918

**Comment by swissspidy** [comment]
If this is only gonna be used for the `wp-*` packages, a private `wp-shared` or `wp-utils` package or something shouldn't be a big deal.

**Comment by mohdsayed** [comment]
Circling back to this ticket after the progress made on https://github.com/GoogleForCreators/web-stories-wp/pull/10452 . There were a few more utility functions dumped in `design-system` only because they were commonly used in more than one package however do not belong to `design-system`. Maybe we can move at least some generic static functions like ( existing and new ) in a utility package?

```js
1. isValidUrl
2. withProtocol
3. stripHTML
4. getKeyboardMovement
5. calcRotatedResizeOffset
6. objectWithout
7. deepMerge
8. domReady
9. uniqueEntriesByKey
10. addQueryArgs
11. noop
12. isNullOrUndefinedOrEmptyString
```

I am expecting more utility functions looking for proper home as we break `story-editor` down into more packages.

**Comment by swissspidy** [comment]
Thanks for this list, very helpful 👍 

For the public packages, if we create a new utility package that's just another dumping ground without cleanly organizing the code. So that would just move a problem around.

> isValidUrl
> withProtocol
> addQueryArgs

There is also `toAbsoluteUrl`

-> a new `url` package?

> stripHTML

There is also `escapeHTML`

-> a new `dom` package?

> domReady

This is only used for `wp-story-editor` and `wp-dashboard`, right? If so, we could:

a) Use the `@wordpress/dom-ready` package there instead. We already use `@wordpress/api-fetch` and this is not a published package.
b) Alternatively, just copy this function to both packages. It's only like 5 lines of code.

> isNullOrUndefinedOrEmptyString

On `main` this is only used within `design-system`, so I think we can just leave it there.

> noop

This is like 20 chars. Every package can just define its own `noop` function for reuse. No need to move that to a shared package.

> getKeyboardMovement

-> a new `keyboard` package together with `useKeyDownEffect` and the like? Maybe `useRovingTabIndex` too.

> calcRotatedResizeOffset

Are there perhaps related math functions that we could group this with?
Maybe something for `units` package? Even though it's not exactly the best fit.

> objectWithout

There is also `objectPick`

Not sure about these two yet. Maybe just duplicate these where needed? They're tiny functions.

> deepMerge

Not sure about this one yet

> uniqueEntriesByKey

This is only used for templates, maybe we can move it to the templates package? Otherwise we could consider duplicating code if needed.

**Comment by mohdsayed** [comment]
> For the public packages, if we create a new utility package that's just another dumping ground without cleanly organizing the code. So that would just move a problem around.

Okay, now I see your concern. This gives me some direction on how to think about these functions.

**Comment by mohdsayed** [comment]
> -> a new keyboard package together with useKeyDownEffect and the like? Maybe useRovingTabIndex too.

Will think about `keyboard` package separately. I think https://github.com/GoogleForCreators/web-stories-wp/pull/10717 should be enough for this ticket. Will see what we should do for the rest of the suggestions in https://github.com/GoogleForCreators/web-stories-wp/pull/10452
