### ISSUE TITLE
Dashboard code cleanup

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9677]
Lighthouse is flagging some unused dashboard js which is interesting and could merit a generic code clean up to make sure t's are crossed and i's are dotted (so to say) given the updates we made this summer.

You can see this by running lighthouse perf on the dashboard before and after making the update. Remember that locally running lighthouse is _not_ the same as running it on staging (our dev environment is wayyyyy slower than prod).

**Comment by samwhale** [comment]
After some investigation, I believe that no changes are necessary now.

Running lighthouse in an incognito window on staging showed us a few javascript files that were unused on first load:
![image.png](https://images.zenhubusercontent.com/5b1032a1348b7966b43421a4/14099740-d405-46d8-8850-02e67814c4df)

Ignoring chrome extensions, we have
1. `wp-dashboard` chunk
2. `wp-admin` load scripts (php)
3. `vendors-wp-dashboard`
4. `lodash`

---

`wp-dashboard` and `vendors-wp-dashboard` are already separated out into their own chunks so we do not need to do anything there.

The `wp-admin` load scripts aren't something that affect the dashboard either, and are also loaded in a different chunk.

Which leaves us with `lodash`. We don't want to load all of `lodash` in, but the app hardly uses it. Turns out that lodash is loaded in the `react-colors` package: ![Screen Shot 2021-11-24 at 8.40.53 AM.png](https://images.zenhubusercontent.com/5b1032a1348b7966b43421a4/64378217-15b2-4d9b-b9cd-9c206c99e659)

![image.png](https://images.zenhubusercontent.com/5b1032a1348b7966b43421a4/6c4e3540-2c34-4e84-b396-815f3237f297)

This is also loaded in apart from the main chunk. I believe for now we don't need to do anything about the files listed in the lighthouse audit.
