### ISSUE TITLE
Use HTML-to-image to generate story poster image

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#9693]
## Feature Description

The HTML-to-image library, is already used in a number of places in the web stories editor. The library is used to convert rendered html to a image. Web stories, require a poster image for them to be a valid web story. There is currently a check list item to reminder users to upload a poster asset. Poster asset are required to be of a size. 

We could add the option to automatically generate a poster image from the first page of the web story. Similar to how we generate poster images from videos.

**Comment by swissspidy** [comment]
Citing the Slack conversation here for completeness:

- Just taking a screenshot of the first page as-is is **not** something we want to do because of content quality issues.
- The first page of the story (the “cover page”) is not the same as the poster image and will look very different. See https://www.youtube.com/watch?v=nKi1QWPwZng
- We could offer users some simple image editor to create the poster image and we'd save them for them
- It would be nice to find a good solution so that creators have one less thing to do / worry about

**Comment by spacedmonkey** [comment]
This PR contain logic to generate a image from a story page https://github.com/google/web-stories-wp/pull/9700
