### ISSUE TITLE
Error Saving and Loading Preview

### ISSUE THREAD

**Issue by mauteurs** [swissspidy/web-stories-wp#9754]
I noticed that the more I add slides, the story shows an error while saving. It didn't affect the story but now, the preview's not even showing. See screenshot. Thank you
![bug](https://user-images.githubusercontent.com/89387433/142607204-c169c24b-ef1c-4e3a-acd2-54ef3e437923.png)

**Comment by swissspidy** [comment]
Hi there

Please note that we only provide support via the WordPress.org support forums at https://wordpress.org/support/plugin/web-stories/. In the future, I recommend you to ask there.

Now since you're already here, in order to be able to help you we need a bit more information:

1. What exactly is the error you see when saving?
2. What's the URL to your story?
3. Which version of the plugin are you using?
4. Does this still happen with all other plugins disabled?

**Comment by mauteurs** [comment]
1) Failed to save the story
2) Not published yet, draft mode
3) Latest
4) Yes, it still happens when all other plugins are deactivated

**Comment by mauteurs** [comment]
The more I add slides, the more errors I get

**Comment by swissspidy** [comment]
"Failed to save the story" can occur if saving to the database failed, for example when there's some server configuration error, a firewall intervening, or a conflicting plugin doing something odd.

To get some more details about this, do this:

1. Open your browser's dev tools by pressing F12
2. Click on "Network"
3. Filter by "wp-json" and "Fetch/XHR"
  ![Screenshot 2021-11-19 at 14 38 08](https://user-images.githubusercontent.com/841956/142631733-1d8b06ab-43e7-42fd-bb60-7d2e0ee3c146.png)
4. Save the story
5. You should now see an entry in the list:
If saving failed, it probably is marked red
  ![Screenshot 2021-11-19 at 14 38 57](https://user-images.githubusercontent.com/841956/142631869-7b8dd906-c924-4952-a85c-e6d15bca6bd9.png)
6. Click on the entry and then "Response" to see details:  
  ![Screenshot 2021-11-19 at 14 39 28](https://user-images.githubusercontent.com/841956/142631986-976f798a-0f8c-4de5-b6ff-8cc7fdf95675.png)
