### ISSUE TITLE
Media fetching test failures

### ISSUE THREAD

**Issue by BrookeGraham** [swissspidy/web-stories-wp#9779]
## Bug Description

When `fixture.screen` isn't ready, we throw an error causing the `MediaPane fetching should fetch 2nd page` karma test to fail. 

## Expected Behaviour

It should wait for the `fixture.screen` results to be present before moving forward. It shouldn't throw an error. 

## Steps to Reproduce

Reported [here](https://github.com/google/web-stories-wp/pull/9757#issuecomment-976565540) 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by ayushnirwal** [comment]
I was trying to fix this test by taking `pagingToken` ( by rendering useLocalMedia ) into consideration and expecting MediaPane to have `LOCAL_MEDIA_PER_PAGE * initialPageToken` number of elements prior to scrolling and `LOCAL_MEDIA_PER_PAGE * (initialPageToken+1)` after.
Although this might fix the test, the real problem was initialPageToken was 2 rather than 1. 

Some debugging and experiments later, found out that after the first set of elements are loaded but not rendered, `loadNextPageIfNeeded` can load an extra set if called, this is why this [delay](https://github.com/google/web-stories-wp/blob/90cb2d2c05eafcd4a5e63e7ade1ddf694437c771/packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js#L115) exists. It doesn't seem to work though and the failure of this test was pointing to this bug ( loading 2 or more sets of elements at once sometimes ).

`loadNextPageIfNeededAfterGalleryRendering` [here](https://github.com/google/web-stories-wp/blob/90cb2d2c05eafcd4a5e63e7ade1ddf694437c771/packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js#L109-L120) seems to have a problem
