### ISSUE TITLE
Right Click Menus: Multiple Elements Clear Styles

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9885]
## Context 

Separated from user feature request #4616 to make sure initial new menus for when multiple elements are selected has isolated test time.

## Feature Description 

When multiple elements are selected and a user right clicks they should get the option to 'clear styles' for all elements selected. 

## Acceptance Criteria 
- New menu option for multiple element right click menu to clear styles that will clear styles for all those elements (same logic as the clear styles for single elements that we have right now) 
- Corresponding tests

**Comment by kkalarickal** [comment]
Tested on https://stories-qa-wordpress-amp.pantheonsite.io/ using #9900 

Status: Passed with Comments

Scenarios:
1. Confirmed right click after selecting multiple elements shows the "clear styles" menu (along with "duplicate") ✔️ 
2. Confirmed selecting "clear styles" results in applied image & video, shapes styles being removed
- this is restricted to styles associated with Settings, Filters, Borders ✔️ 
- any other changes (e.g. alignment, animation, etc) are NOT cleared ❓
- not possible to clear text styles ❓ 
3. Confirmed that it is possible to undo the clear styles action

Comments: 
1. As an editor who has saved text styles and applied them to a new text element, why is it that styles associated with text cannot be cleared as part of this workflow ?
2. As a novice user who has added an image without changing any settings, why is it possible to clear styles?
3.  As a user, i am confused by being able to "reset element properties" and "clear styles" since one seems to be redundant.

Cc; @swissspidy @samwhale @bmattb

**Comment by samwhale** [comment]
Hi @kkalarickal!

Thank you for the super thorough review.. I can get to the two points that are a mystery still.

>any other changes (e.g. alignment, animation, etc) are NOT cleared

In #8496 it was outlined that there will only be a base set of styles that are reset. Other styles weren't added yet
![image](https://user-images.githubusercontent.com/22185279/146422287-b4cdb715-1c94-49e2-9664-2996517e81ff.png)

>not possible to clear text styles
>
>As an editor who has saved text styles and applied them to a new text element, why is it that styles associated with text cannot be cleared as part of this workflow ?

I've been searching for something about this and I think that it's never existed! When I wrote this PR I saw that text styles don't have a way of being cleared so I left it out too.

At the moment this is working within existing expectations of the app. Added a ticket for this here: #10018

---

>As a novice user who has added an image without changing any settings, why is it possible to clear styles?

If there aren't any changes to the image we should probably disable the action. thoughts @agingoldseco?

>As a user, i am confused by being able to "reset element properties" and "clear styles" since one seems to be redundant.

I'll defer to @agingoldseco about the wording here. Seems redundant and maybe we can align on copy as well. I think that should be done in another ticket if we decide to change it.
