### ISSUE TITLE
Saving text background color saves text color instead

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9891]
## Bug Description

When I want to save the text element's background color, it saves the text color instead.

## Expected Behaviour

The bg color should be saved.

## Steps to Reproduce

1. Insert text element
2. Change bg color
3. Try to save bg color

## Screenshots

https://user-images.githubusercontent.com/841956/144714656-96795a83-f5e4-44a5-81fe-2f772cd04dec.mov

## Additional Context

- Plugin Version: 1.16.0-alpha
- WordPress Version: 5.9 Beta
- Operating System: macOS
- Browser: Chrome

**Comment by miina** [comment]
@swissspidy This was like it by design -- the user can only save the text color into the Saved / Current colors. If the user wants to save background color, the Saved Styles needs to be used instead. Same was for applying the colors, it was only applied to the text, not the background when using the Color Picker's Saved Colors.

Not a bug, a feature 😛 

If we switch to using the background color, how can the text color be saved?

Might require some Product / UX thoughts to resolve this.

~cc @gajasinski / @agingoldseco Thoughts on if the current behaviour needs changes?~

**Comment by miina** [comment]
Hm, okay, now I see, the idea is that since the open Color Picker is for the background color specifically, it should also apply it to the background color, and not the text.

Alright, this might need reworking the logic there a bit.

**Comment by amovar18** [comment]
Had an idea about the logic we could pull the `backgroundColor` from the `selectedElement` pass down a prop like `isBackgroundColor` from `BackgroundControls.js` and have a condition like:
``` 
if(isBackground){
   colors.pop();
   colors.push(...backgroundColor);
}
```
I could create a quick POC demonstration.

**Comment by miina** [comment]
The `Color` input already has `changedStyle` as one of the properties, haven't looked into it yet but we could perhaps use that somehow and skip adding additional props.

**Comment by amovar18** [comment]
> The `Color` input already has `changedStyle` as one of the properties, haven't looked into it yet but we could perhaps use that somehow and skip adding additional props.

Just looked into it, instead of checking `isBackground` and passing an extra prop we can check the value of `changedStyle`.

**Comment by amovar18** [comment]
We could use the prop `changedStyle` and pass it from `Backgroundcontrols`->`Color`->`ColorInput`. Since `changedStyle` is not being passed from `Backgoundcontrols` till `ColorInput` so we make use of it. I might have an early implementation of the idea.

**Comment by amovar18** [comment]
@Trapsta Can I take this if it hasnt been worked on yet?

**Comment by Trapsta** [comment]
sorry @amovar18 this is already in progress

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/post.php?post=15708&action=edit#page=%252237b6d1bc-4856-40e5-82a9-4bcf4a7919e7%2522, using PR #10028.

1. Opened link above
2. Clicked on the + sign beside "T" (text)
3. Entered a text
4. Clicked on Fill (on the right side panel)
5. Changed color of the background
6. Changed color of the text
7. Changed color of the page background


https://user-images.githubusercontent.com/96055551/148824102-a82ec694-f83f-42e1-bc52-e2f37b84d024.mp4

**Comment by swissspidy** [comment]
I don't think that adequately tests the original issue and the fix from #10028

The QA instructions were as follows:

This PR can be tested by following these steps:

Insert text element
Change bg color
Try to save bg color
make sure the correct color is added to both the local and global colors.
Make sure saving the text color also works correctly.

In your video, you're just changing the colors by picking an already saved color.

**Comment by felipebochehin87** [comment]
Thanks @swissspidy 

Retested:

1. Inserted text
2. Changed background color to a custom color
3. Saved background color (current story and saved colors)
4. **However**, for the text color, I need to close and reopen the color tray so that I can save the new color (it starts on the 55th second). Should we raise a new bug/PR for this?


https://user-images.githubusercontent.com/96055551/148836494-83516593-4059-4bc1-a826-d2af4d182ceb.mp4

**Comment by swissspidy** [comment]
Not sure what the I am looking at / what the issue is exactly there 🤔 

@miina Could you perhaps chime in?

**Comment by felipebochehin87** [comment]
What I did was:

1. I changed the text color to a custom color
2. I clicked on + to save the color to the current story color - no effect
3. I closed the color tray, reopened and clicked again on + to save the color to the current story color - no effect
4. I clicked somewhere else, out of the text box
5. I clicked again on the text, clicked on color to open the color tray and clicked on + to save the color to the current story color - color is saved

**Comment by kkalarickal** [comment]
@felipebochehin87 - It looks like the original issue that this PR addresses is fixed and your tests confirm this. So adding a custom color to the text-box and then trying to save that custom text-box color (local & global) works.

Next is the question of saving the custom color applied to a text element -- at 1:07 in your video, you seem to be clicking the Add to Saved Colors button. This will add to the global list and you cannot add once again if its already there. Regarding the add to local list, I agree that in your video the first attempt did not work. But that could be due to a delayed response or something else.

When I repeated the saving-custom-color-applied-to-text-element on a new story, I was able to add the custom color without any delay.

I would recommend you confirm that you are seeing this issue repeatedly and can reproduce it consistently. Perhaps there is something different in your setup that is causing this. If you can narrow that down then it will allos dev's to find a fix.

**Comment by felipebochehin87** [comment]
@kkalarickal this bug fix is ok, my question is about the text color. I reproduced it again. My question is: should we raise a new bug for this? Here it is, happening again.


https://user-images.githubusercontent.com/96055551/148847549-8e88fd5f-b843-4247-8ad5-6510d2738b51.mp4

**Comment by felipebochehin87** [comment]
@swissspidy @miina @kkalarickal I'll create a new issue for this bug I mentioned above. This fix is working as expected. Thanks! :)
