### ISSUE TITLE
Can clear the gradient of an image that doesn't load using the context menu

### ISSUE THREAD

**Issue by samwhale** [swissspidy/web-stories-wp#9899]
## Bug Description

The gradient styles for an image that doesn't load can be cleared using the `Clear image styles` button in the context menu.

## Expected Behaviour

Not sure if that's expected, but seems strange that those styles can be changed.

## Steps to Reproduce

1. Add an image to the canvas that won't load (I used a slow connection speed. Broken links should work too)
2. Right click the image
3. Click `Clear Image Styles`
4. See the gradient clear

## Screenshots

![lmao](https://user-images.githubusercontent.com/22185279/144837890-430b82ee-afad-431f-969e-a769bfe5fff7.gif)

## Additional Context

- Plugin Version: 1.16.0
- WordPress Version: 5.8.2
- Operating System: macOSX Big Sur 11.5.2
- Browser: Chrome

**Comment by miina** [comment]
@BrittanyIRL This might also be for you since this has to do with the Right-Click menu, thoughts?

**Comment by BrittanyIRL** [comment]
🤔  this is an interesting one because the right click menu is just clearing styles and if an image doesn't load then that gradient is just applied to it? It feels like that should be separated outside of the element so it's not something to clear? I'm happy to take this for pea pod but I think we should figure out what the solution is beforehand because this feels rather slippery to me.


https://github.com/google/web-stories-wp/blob/main/packages/story-editor/src/app/rightClickMenu/provider.js#L573-L615

**Comment by miina** [comment]
> this is an interesting one because the right click menu is just clearing styles and if an image doesn't load then that gradient is just applied to it? It feels like that should be separated outside of the element so it's not something to clear? I'm happy to take this for pea pod but I think we should figure out what the solution is beforehand because this feels rather slippery to me.

Hm, that's an odd one indeed, I also wasn't aware that the gradient is by default added to the image while it's loading (or as a default?). Looks like it has nothing to do with the right-click menu itself then (we could also keep it for Prometheus in this case if that makes more sense, I misunderstood the issue at first)

@swissspidy / @spacedmonkey Since this has to do with media -- are you aware of gradient being added to the media element while loading, do you happen to know if it's something that was purposefully added?

If not and no one knows why it's happening, we should probably just ensure no gradient is applied to media by default.

**Comment by swissspidy** [comment]
Do you happen to know where in the code this gradient is being applied? Then I could dig into `git blame` history a bit...

If this was done to improve the UX while images are loading, then I don't see why this styling is added to the element itself.

**Comment by miina** [comment]
> Do you happen to know where in the code this gradient is being applied? Then I could dig into git blame history a bit...

I haven't looked into it yet -- was just wondering if this was something purposeful (e.g. to improve the UX as you mentioned) or if we could remove it fully. I'll take a look to see where it's happening (tomorrow probably).

**Comment by swissspidy** [comment]
Is this still relevant?

**Comment by miina** [comment]
Doesn't seem to be happening currently anymore. Closing.
