### ISSUE TITLE
Video Captions: Enable new captions in editor by default

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#9938]
## Task Description

#9699 added new video captions in the editor, but behind a feature flag.

We want to enable this by default eventually.

**Comment by felipebochehin87** [comment]
@swissspidy please, I have one question about this one. I saw the steps on PR #10056 and the step #5 says: "See that the captions are displayed on top of all other elements and always at the same position on the canvas". Does it mean that the caption should be displayed at the same place on both editor and preview? I'm asking because on the editor I see the caption at the bottom of the video square, and on preview screen I see it at the bottom of the screen. And on the editor, if I have an image, this image hides the caption. Is that ok?


https://user-images.githubusercontent.com/96055551/149025879-30cc1e2a-c011-4879-b064-e1d5239fbf8f.mp4

**Comment by swissspidy** [comment]
@felipebochehin87 please try again. I forgot that #10056 wasn't really testable on the QA environment. now it should work.

The appearance should be identical as on the preview, in the same place.

**Comment by felipebochehin87** [comment]
Thanks @swissspidy.

Tested against https://stories-qa-wordpress-amp.pantheonsite.io/web-stories, using PR #10056.

1. Opened the editor
2. Added a new video to a story
3. Added captions to the video
4. Played the video in the editor - captions displayed at the bottom of the screen
5. Opened preview screen - captions displayed at the bottom of the screen

![preview](https://user-images.githubusercontent.com/96055551/149032246-e50ba745-fc4d-4951-a310-d7f41cfe530b.png)
![editor](https://user-images.githubusercontent.com/96055551/149032254-4b8cb3d9-dbc2-4a47-b763-b4fe9b54a71c.png)
