### ISSUE TITLE
 Web Story is invalid  for https://share-ask.com/web-stories/hot-debates/

### ISSUE THREAD

**Issue by bpshbp** [swissspidy/web-stories-wp#9988]
Im getting  Web Story is invalid  for https://share-ask.com/web-stories/hot-debates/ error plz help pfa
![image](https://user-images.githubusercontent.com/7966980/146006687-6421b084-3a5b-41b0-ae0e-bcfca5d8bbab.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
Hi there

We only provide support via the official [WordPress.org support forums](https://wordpress.org/support/plugin/web-stories/). Please ask your question there next time.

Your story is invalid because you have not added a poster image to the story. Add a poster, and the issue goes away.

A poster image is required, as is indicated by the pre-publish checklist.

We highly recommend following the checklist before publishing and reporting potential bugs.

**Comment by bpshbp** [comment]
The issue doesnt go pfa

![image](https://user-images.githubusercontent.com/7966980/146938884-ed6d32de-f4ac-4e61-9181-a1ff7e45faec.png)

**Comment by mxbclang** [comment]
@bpshbp I see that you've [opened a topic on our support forum](https://wordpress.org/support/topic/web-story-is-invalid-for-https-share-ask-com-web-stories-hot-debates/), so we will discuss further with you there. Thanks!
